package com.lexiangmiao.sample.mybatis.repository.cee;

import com.lexiangmiao.sample.mybatis.domain.cee.SchoolPlan;
import com.lexiangmiao.sample.mybatis.domain.cee.SchoolPlanExample;
import com.lexiangmiao.sample.mybatis.domain.cee.SchoolPlanKey;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SchoolPlanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_plan
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    long countByExample(SchoolPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_plan
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    int deleteByExample(SchoolPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_plan
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    int deleteByPrimaryKey(SchoolPlanKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_plan
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    int insert(SchoolPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_plan
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    int insertSelective(SchoolPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_plan
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    List<SchoolPlan> selectByExample(SchoolPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_plan
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    SchoolPlan selectByPrimaryKey(SchoolPlanKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_plan
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    int updateByExampleSelective(@Param("record") SchoolPlan record, @Param("example") SchoolPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_plan
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    int updateByExample(@Param("record") SchoolPlan record, @Param("example") SchoolPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_plan
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    int updateByPrimaryKeySelective(SchoolPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_plan
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    int updateByPrimaryKey(SchoolPlan record);
}