package com.lexiangmiao.sample.mybatis.domain.cee;

import java.util.ArrayList;
import java.util.List;

public class ProvincialScoreExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table provincial_score
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table provincial_score
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table provincial_score
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provincial_score
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public ProvincialScoreExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provincial_score
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provincial_score
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provincial_score
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provincial_score
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provincial_score
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provincial_score
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provincial_score
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provincial_score
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provincial_score
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provincial_score
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table provincial_score
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andProvincialScoreIdIsNull() {
            addCriterion("provincial_score_id is null");
            return (Criteria) this;
        }

        public Criteria andProvincialScoreIdIsNotNull() {
            addCriterion("provincial_score_id is not null");
            return (Criteria) this;
        }

        public Criteria andProvincialScoreIdEqualTo(Long value) {
            addCriterion("provincial_score_id =", value, "provincialScoreId");
            return (Criteria) this;
        }

        public Criteria andProvincialScoreIdNotEqualTo(Long value) {
            addCriterion("provincial_score_id <>", value, "provincialScoreId");
            return (Criteria) this;
        }

        public Criteria andProvincialScoreIdGreaterThan(Long value) {
            addCriterion("provincial_score_id >", value, "provincialScoreId");
            return (Criteria) this;
        }

        public Criteria andProvincialScoreIdGreaterThanOrEqualTo(Long value) {
            addCriterion("provincial_score_id >=", value, "provincialScoreId");
            return (Criteria) this;
        }

        public Criteria andProvincialScoreIdLessThan(Long value) {
            addCriterion("provincial_score_id <", value, "provincialScoreId");
            return (Criteria) this;
        }

        public Criteria andProvincialScoreIdLessThanOrEqualTo(Long value) {
            addCriterion("provincial_score_id <=", value, "provincialScoreId");
            return (Criteria) this;
        }

        public Criteria andProvincialScoreIdIn(List<Long> values) {
            addCriterion("provincial_score_id in", values, "provincialScoreId");
            return (Criteria) this;
        }

        public Criteria andProvincialScoreIdNotIn(List<Long> values) {
            addCriterion("provincial_score_id not in", values, "provincialScoreId");
            return (Criteria) this;
        }

        public Criteria andProvincialScoreIdBetween(Long value1, Long value2) {
            addCriterion("provincial_score_id between", value1, value2, "provincialScoreId");
            return (Criteria) this;
        }

        public Criteria andProvincialScoreIdNotBetween(Long value1, Long value2) {
            addCriterion("provincial_score_id not between", value1, value2, "provincialScoreId");
            return (Criteria) this;
        }

        public Criteria andSchoolIdIsNull() {
            addCriterion("school_id is null");
            return (Criteria) this;
        }

        public Criteria andSchoolIdIsNotNull() {
            addCriterion("school_id is not null");
            return (Criteria) this;
        }

        public Criteria andSchoolIdEqualTo(String value) {
            addCriterion("school_id =", value, "schoolId");
            return (Criteria) this;
        }

        public Criteria andSchoolIdNotEqualTo(String value) {
            addCriterion("school_id <>", value, "schoolId");
            return (Criteria) this;
        }

        public Criteria andSchoolIdGreaterThan(String value) {
            addCriterion("school_id >", value, "schoolId");
            return (Criteria) this;
        }

        public Criteria andSchoolIdGreaterThanOrEqualTo(String value) {
            addCriterion("school_id >=", value, "schoolId");
            return (Criteria) this;
        }

        public Criteria andSchoolIdLessThan(String value) {
            addCriterion("school_id <", value, "schoolId");
            return (Criteria) this;
        }

        public Criteria andSchoolIdLessThanOrEqualTo(String value) {
            addCriterion("school_id <=", value, "schoolId");
            return (Criteria) this;
        }

        public Criteria andSchoolIdLike(String value) {
            addCriterion("school_id like", value, "schoolId");
            return (Criteria) this;
        }

        public Criteria andSchoolIdNotLike(String value) {
            addCriterion("school_id not like", value, "schoolId");
            return (Criteria) this;
        }

        public Criteria andSchoolIdIn(List<String> values) {
            addCriterion("school_id in", values, "schoolId");
            return (Criteria) this;
        }

        public Criteria andSchoolIdNotIn(List<String> values) {
            addCriterion("school_id not in", values, "schoolId");
            return (Criteria) this;
        }

        public Criteria andSchoolIdBetween(String value1, String value2) {
            addCriterion("school_id between", value1, value2, "schoolId");
            return (Criteria) this;
        }

        public Criteria andSchoolIdNotBetween(String value1, String value2) {
            addCriterion("school_id not between", value1, value2, "schoolId");
            return (Criteria) this;
        }

        public Criteria andSchoolNameIsNull() {
            addCriterion("school_name is null");
            return (Criteria) this;
        }

        public Criteria andSchoolNameIsNotNull() {
            addCriterion("school_name is not null");
            return (Criteria) this;
        }

        public Criteria andSchoolNameEqualTo(String value) {
            addCriterion("school_name =", value, "schoolName");
            return (Criteria) this;
        }

        public Criteria andSchoolNameNotEqualTo(String value) {
            addCriterion("school_name <>", value, "schoolName");
            return (Criteria) this;
        }

        public Criteria andSchoolNameGreaterThan(String value) {
            addCriterion("school_name >", value, "schoolName");
            return (Criteria) this;
        }

        public Criteria andSchoolNameGreaterThanOrEqualTo(String value) {
            addCriterion("school_name >=", value, "schoolName");
            return (Criteria) this;
        }

        public Criteria andSchoolNameLessThan(String value) {
            addCriterion("school_name <", value, "schoolName");
            return (Criteria) this;
        }

        public Criteria andSchoolNameLessThanOrEqualTo(String value) {
            addCriterion("school_name <=", value, "schoolName");
            return (Criteria) this;
        }

        public Criteria andSchoolNameLike(String value) {
            addCriterion("school_name like", value, "schoolName");
            return (Criteria) this;
        }

        public Criteria andSchoolNameNotLike(String value) {
            addCriterion("school_name not like", value, "schoolName");
            return (Criteria) this;
        }

        public Criteria andSchoolNameIn(List<String> values) {
            addCriterion("school_name in", values, "schoolName");
            return (Criteria) this;
        }

        public Criteria andSchoolNameNotIn(List<String> values) {
            addCriterion("school_name not in", values, "schoolName");
            return (Criteria) this;
        }

        public Criteria andSchoolNameBetween(String value1, String value2) {
            addCriterion("school_name between", value1, value2, "schoolName");
            return (Criteria) this;
        }

        public Criteria andSchoolNameNotBetween(String value1, String value2) {
            addCriterion("school_name not between", value1, value2, "schoolName");
            return (Criteria) this;
        }

        public Criteria andProvinceIdIsNull() {
            addCriterion("province_id is null");
            return (Criteria) this;
        }

        public Criteria andProvinceIdIsNotNull() {
            addCriterion("province_id is not null");
            return (Criteria) this;
        }

        public Criteria andProvinceIdEqualTo(String value) {
            addCriterion("province_id =", value, "provinceId");
            return (Criteria) this;
        }

        public Criteria andProvinceIdNotEqualTo(String value) {
            addCriterion("province_id <>", value, "provinceId");
            return (Criteria) this;
        }

        public Criteria andProvinceIdGreaterThan(String value) {
            addCriterion("province_id >", value, "provinceId");
            return (Criteria) this;
        }

        public Criteria andProvinceIdGreaterThanOrEqualTo(String value) {
            addCriterion("province_id >=", value, "provinceId");
            return (Criteria) this;
        }

        public Criteria andProvinceIdLessThan(String value) {
            addCriterion("province_id <", value, "provinceId");
            return (Criteria) this;
        }

        public Criteria andProvinceIdLessThanOrEqualTo(String value) {
            addCriterion("province_id <=", value, "provinceId");
            return (Criteria) this;
        }

        public Criteria andProvinceIdLike(String value) {
            addCriterion("province_id like", value, "provinceId");
            return (Criteria) this;
        }

        public Criteria andProvinceIdNotLike(String value) {
            addCriterion("province_id not like", value, "provinceId");
            return (Criteria) this;
        }

        public Criteria andProvinceIdIn(List<String> values) {
            addCriterion("province_id in", values, "provinceId");
            return (Criteria) this;
        }

        public Criteria andProvinceIdNotIn(List<String> values) {
            addCriterion("province_id not in", values, "provinceId");
            return (Criteria) this;
        }

        public Criteria andProvinceIdBetween(String value1, String value2) {
            addCriterion("province_id between", value1, value2, "provinceId");
            return (Criteria) this;
        }

        public Criteria andProvinceIdNotBetween(String value1, String value2) {
            addCriterion("province_id not between", value1, value2, "provinceId");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andBatchIsNull() {
            addCriterion("batch is null");
            return (Criteria) this;
        }

        public Criteria andBatchIsNotNull() {
            addCriterion("batch is not null");
            return (Criteria) this;
        }

        public Criteria andBatchEqualTo(String value) {
            addCriterion("batch =", value, "batch");
            return (Criteria) this;
        }

        public Criteria andBatchNotEqualTo(String value) {
            addCriterion("batch <>", value, "batch");
            return (Criteria) this;
        }

        public Criteria andBatchGreaterThan(String value) {
            addCriterion("batch >", value, "batch");
            return (Criteria) this;
        }

        public Criteria andBatchGreaterThanOrEqualTo(String value) {
            addCriterion("batch >=", value, "batch");
            return (Criteria) this;
        }

        public Criteria andBatchLessThan(String value) {
            addCriterion("batch <", value, "batch");
            return (Criteria) this;
        }

        public Criteria andBatchLessThanOrEqualTo(String value) {
            addCriterion("batch <=", value, "batch");
            return (Criteria) this;
        }

        public Criteria andBatchLike(String value) {
            addCriterion("batch like", value, "batch");
            return (Criteria) this;
        }

        public Criteria andBatchNotLike(String value) {
            addCriterion("batch not like", value, "batch");
            return (Criteria) this;
        }

        public Criteria andBatchIn(List<String> values) {
            addCriterion("batch in", values, "batch");
            return (Criteria) this;
        }

        public Criteria andBatchNotIn(List<String> values) {
            addCriterion("batch not in", values, "batch");
            return (Criteria) this;
        }

        public Criteria andBatchBetween(String value1, String value2) {
            addCriterion("batch between", value1, value2, "batch");
            return (Criteria) this;
        }

        public Criteria andBatchNotBetween(String value1, String value2) {
            addCriterion("batch not between", value1, value2, "batch");
            return (Criteria) this;
        }

        public Criteria andZslxIsNull() {
            addCriterion("zslx is null");
            return (Criteria) this;
        }

        public Criteria andZslxIsNotNull() {
            addCriterion("zslx is not null");
            return (Criteria) this;
        }

        public Criteria andZslxEqualTo(Integer value) {
            addCriterion("zslx =", value, "zslx");
            return (Criteria) this;
        }

        public Criteria andZslxNotEqualTo(Integer value) {
            addCriterion("zslx <>", value, "zslx");
            return (Criteria) this;
        }

        public Criteria andZslxGreaterThan(Integer value) {
            addCriterion("zslx >", value, "zslx");
            return (Criteria) this;
        }

        public Criteria andZslxGreaterThanOrEqualTo(Integer value) {
            addCriterion("zslx >=", value, "zslx");
            return (Criteria) this;
        }

        public Criteria andZslxLessThan(Integer value) {
            addCriterion("zslx <", value, "zslx");
            return (Criteria) this;
        }

        public Criteria andZslxLessThanOrEqualTo(Integer value) {
            addCriterion("zslx <=", value, "zslx");
            return (Criteria) this;
        }

        public Criteria andZslxIn(List<Integer> values) {
            addCriterion("zslx in", values, "zslx");
            return (Criteria) this;
        }

        public Criteria andZslxNotIn(List<Integer> values) {
            addCriterion("zslx not in", values, "zslx");
            return (Criteria) this;
        }

        public Criteria andZslxBetween(Integer value1, Integer value2) {
            addCriterion("zslx between", value1, value2, "zslx");
            return (Criteria) this;
        }

        public Criteria andZslxNotBetween(Integer value1, Integer value2) {
            addCriterion("zslx not between", value1, value2, "zslx");
            return (Criteria) this;
        }

        public Criteria andXclevelIsNull() {
            addCriterion("xclevel is null");
            return (Criteria) this;
        }

        public Criteria andXclevelIsNotNull() {
            addCriterion("xclevel is not null");
            return (Criteria) this;
        }

        public Criteria andXclevelEqualTo(String value) {
            addCriterion("xclevel =", value, "xclevel");
            return (Criteria) this;
        }

        public Criteria andXclevelNotEqualTo(String value) {
            addCriterion("xclevel <>", value, "xclevel");
            return (Criteria) this;
        }

        public Criteria andXclevelGreaterThan(String value) {
            addCriterion("xclevel >", value, "xclevel");
            return (Criteria) this;
        }

        public Criteria andXclevelGreaterThanOrEqualTo(String value) {
            addCriterion("xclevel >=", value, "xclevel");
            return (Criteria) this;
        }

        public Criteria andXclevelLessThan(String value) {
            addCriterion("xclevel <", value, "xclevel");
            return (Criteria) this;
        }

        public Criteria andXclevelLessThanOrEqualTo(String value) {
            addCriterion("xclevel <=", value, "xclevel");
            return (Criteria) this;
        }

        public Criteria andXclevelLike(String value) {
            addCriterion("xclevel like", value, "xclevel");
            return (Criteria) this;
        }

        public Criteria andXclevelNotLike(String value) {
            addCriterion("xclevel not like", value, "xclevel");
            return (Criteria) this;
        }

        public Criteria andXclevelIn(List<String> values) {
            addCriterion("xclevel in", values, "xclevel");
            return (Criteria) this;
        }

        public Criteria andXclevelNotIn(List<String> values) {
            addCriterion("xclevel not in", values, "xclevel");
            return (Criteria) this;
        }

        public Criteria andXclevelBetween(String value1, String value2) {
            addCriterion("xclevel between", value1, value2, "xclevel");
            return (Criteria) this;
        }

        public Criteria andXclevelNotBetween(String value1, String value2) {
            addCriterion("xclevel not between", value1, value2, "xclevel");
            return (Criteria) this;
        }

        public Criteria andMaxIsNull() {
            addCriterion("max is null");
            return (Criteria) this;
        }

        public Criteria andMaxIsNotNull() {
            addCriterion("max is not null");
            return (Criteria) this;
        }

        public Criteria andMaxEqualTo(Double value) {
            addCriterion("max =", value, "max");
            return (Criteria) this;
        }

        public Criteria andMaxNotEqualTo(Double value) {
            addCriterion("max <>", value, "max");
            return (Criteria) this;
        }

        public Criteria andMaxGreaterThan(Double value) {
            addCriterion("max >", value, "max");
            return (Criteria) this;
        }

        public Criteria andMaxGreaterThanOrEqualTo(Double value) {
            addCriterion("max >=", value, "max");
            return (Criteria) this;
        }

        public Criteria andMaxLessThan(Double value) {
            addCriterion("max <", value, "max");
            return (Criteria) this;
        }

        public Criteria andMaxLessThanOrEqualTo(Double value) {
            addCriterion("max <=", value, "max");
            return (Criteria) this;
        }

        public Criteria andMaxIn(List<Double> values) {
            addCriterion("max in", values, "max");
            return (Criteria) this;
        }

        public Criteria andMaxNotIn(List<Double> values) {
            addCriterion("max not in", values, "max");
            return (Criteria) this;
        }

        public Criteria andMaxBetween(Double value1, Double value2) {
            addCriterion("max between", value1, value2, "max");
            return (Criteria) this;
        }

        public Criteria andMaxNotBetween(Double value1, Double value2) {
            addCriterion("max not between", value1, value2, "max");
            return (Criteria) this;
        }

        public Criteria andMinSectionIsNull() {
            addCriterion("min_section is null");
            return (Criteria) this;
        }

        public Criteria andMinSectionIsNotNull() {
            addCriterion("min_section is not null");
            return (Criteria) this;
        }

        public Criteria andMinSectionEqualTo(Integer value) {
            addCriterion("min_section =", value, "minSection");
            return (Criteria) this;
        }

        public Criteria andMinSectionNotEqualTo(Integer value) {
            addCriterion("min_section <>", value, "minSection");
            return (Criteria) this;
        }

        public Criteria andMinSectionGreaterThan(Integer value) {
            addCriterion("min_section >", value, "minSection");
            return (Criteria) this;
        }

        public Criteria andMinSectionGreaterThanOrEqualTo(Integer value) {
            addCriterion("min_section >=", value, "minSection");
            return (Criteria) this;
        }

        public Criteria andMinSectionLessThan(Integer value) {
            addCriterion("min_section <", value, "minSection");
            return (Criteria) this;
        }

        public Criteria andMinSectionLessThanOrEqualTo(Integer value) {
            addCriterion("min_section <=", value, "minSection");
            return (Criteria) this;
        }

        public Criteria andMinSectionIn(List<Integer> values) {
            addCriterion("min_section in", values, "minSection");
            return (Criteria) this;
        }

        public Criteria andMinSectionNotIn(List<Integer> values) {
            addCriterion("min_section not in", values, "minSection");
            return (Criteria) this;
        }

        public Criteria andMinSectionBetween(Integer value1, Integer value2) {
            addCriterion("min_section between", value1, value2, "minSection");
            return (Criteria) this;
        }

        public Criteria andMinSectionNotBetween(Integer value1, Integer value2) {
            addCriterion("min_section not between", value1, value2, "minSection");
            return (Criteria) this;
        }

        public Criteria andMinIsNull() {
            addCriterion("min is null");
            return (Criteria) this;
        }

        public Criteria andMinIsNotNull() {
            addCriterion("min is not null");
            return (Criteria) this;
        }

        public Criteria andMinEqualTo(Double value) {
            addCriterion("min =", value, "min");
            return (Criteria) this;
        }

        public Criteria andMinNotEqualTo(Double value) {
            addCriterion("min <>", value, "min");
            return (Criteria) this;
        }

        public Criteria andMinGreaterThan(Double value) {
            addCriterion("min >", value, "min");
            return (Criteria) this;
        }

        public Criteria andMinGreaterThanOrEqualTo(Double value) {
            addCriterion("min >=", value, "min");
            return (Criteria) this;
        }

        public Criteria andMinLessThan(Double value) {
            addCriterion("min <", value, "min");
            return (Criteria) this;
        }

        public Criteria andMinLessThanOrEqualTo(Double value) {
            addCriterion("min <=", value, "min");
            return (Criteria) this;
        }

        public Criteria andMinIn(List<Double> values) {
            addCriterion("min in", values, "min");
            return (Criteria) this;
        }

        public Criteria andMinNotIn(List<Double> values) {
            addCriterion("min not in", values, "min");
            return (Criteria) this;
        }

        public Criteria andMinBetween(Double value1, Double value2) {
            addCriterion("min between", value1, value2, "min");
            return (Criteria) this;
        }

        public Criteria andMinNotBetween(Double value1, Double value2) {
            addCriterion("min not between", value1, value2, "min");
            return (Criteria) this;
        }

        public Criteria andAverageIsNull() {
            addCriterion("average is null");
            return (Criteria) this;
        }

        public Criteria andAverageIsNotNull() {
            addCriterion("average is not null");
            return (Criteria) this;
        }

        public Criteria andAverageEqualTo(Double value) {
            addCriterion("average =", value, "average");
            return (Criteria) this;
        }

        public Criteria andAverageNotEqualTo(Double value) {
            addCriterion("average <>", value, "average");
            return (Criteria) this;
        }

        public Criteria andAverageGreaterThan(Double value) {
            addCriterion("average >", value, "average");
            return (Criteria) this;
        }

        public Criteria andAverageGreaterThanOrEqualTo(Double value) {
            addCriterion("average >=", value, "average");
            return (Criteria) this;
        }

        public Criteria andAverageLessThan(Double value) {
            addCriterion("average <", value, "average");
            return (Criteria) this;
        }

        public Criteria andAverageLessThanOrEqualTo(Double value) {
            addCriterion("average <=", value, "average");
            return (Criteria) this;
        }

        public Criteria andAverageIn(List<Double> values) {
            addCriterion("average in", values, "average");
            return (Criteria) this;
        }

        public Criteria andAverageNotIn(List<Double> values) {
            addCriterion("average not in", values, "average");
            return (Criteria) this;
        }

        public Criteria andAverageBetween(Double value1, Double value2) {
            addCriterion("average between", value1, value2, "average");
            return (Criteria) this;
        }

        public Criteria andAverageNotBetween(Double value1, Double value2) {
            addCriterion("average not between", value1, value2, "average");
            return (Criteria) this;
        }

        public Criteria andFilingIsNull() {
            addCriterion("filing is null");
            return (Criteria) this;
        }

        public Criteria andFilingIsNotNull() {
            addCriterion("filing is not null");
            return (Criteria) this;
        }

        public Criteria andFilingEqualTo(String value) {
            addCriterion("filing =", value, "filing");
            return (Criteria) this;
        }

        public Criteria andFilingNotEqualTo(String value) {
            addCriterion("filing <>", value, "filing");
            return (Criteria) this;
        }

        public Criteria andFilingGreaterThan(String value) {
            addCriterion("filing >", value, "filing");
            return (Criteria) this;
        }

        public Criteria andFilingGreaterThanOrEqualTo(String value) {
            addCriterion("filing >=", value, "filing");
            return (Criteria) this;
        }

        public Criteria andFilingLessThan(String value) {
            addCriterion("filing <", value, "filing");
            return (Criteria) this;
        }

        public Criteria andFilingLessThanOrEqualTo(String value) {
            addCriterion("filing <=", value, "filing");
            return (Criteria) this;
        }

        public Criteria andFilingLike(String value) {
            addCriterion("filing like", value, "filing");
            return (Criteria) this;
        }

        public Criteria andFilingNotLike(String value) {
            addCriterion("filing not like", value, "filing");
            return (Criteria) this;
        }

        public Criteria andFilingIn(List<String> values) {
            addCriterion("filing in", values, "filing");
            return (Criteria) this;
        }

        public Criteria andFilingNotIn(List<String> values) {
            addCriterion("filing not in", values, "filing");
            return (Criteria) this;
        }

        public Criteria andFilingBetween(String value1, String value2) {
            addCriterion("filing between", value1, value2, "filing");
            return (Criteria) this;
        }

        public Criteria andFilingNotBetween(String value1, String value2) {
            addCriterion("filing not between", value1, value2, "filing");
            return (Criteria) this;
        }

        public Criteria andTypeControlIsNull() {
            addCriterion("type_control is null");
            return (Criteria) this;
        }

        public Criteria andTypeControlIsNotNull() {
            addCriterion("type_control is not null");
            return (Criteria) this;
        }

        public Criteria andTypeControlEqualTo(String value) {
            addCriterion("type_control =", value, "typeControl");
            return (Criteria) this;
        }

        public Criteria andTypeControlNotEqualTo(String value) {
            addCriterion("type_control <>", value, "typeControl");
            return (Criteria) this;
        }

        public Criteria andTypeControlGreaterThan(String value) {
            addCriterion("type_control >", value, "typeControl");
            return (Criteria) this;
        }

        public Criteria andTypeControlGreaterThanOrEqualTo(String value) {
            addCriterion("type_control >=", value, "typeControl");
            return (Criteria) this;
        }

        public Criteria andTypeControlLessThan(String value) {
            addCriterion("type_control <", value, "typeControl");
            return (Criteria) this;
        }

        public Criteria andTypeControlLessThanOrEqualTo(String value) {
            addCriterion("type_control <=", value, "typeControl");
            return (Criteria) this;
        }

        public Criteria andTypeControlLike(String value) {
            addCriterion("type_control like", value, "typeControl");
            return (Criteria) this;
        }

        public Criteria andTypeControlNotLike(String value) {
            addCriterion("type_control not like", value, "typeControl");
            return (Criteria) this;
        }

        public Criteria andTypeControlIn(List<String> values) {
            addCriterion("type_control in", values, "typeControl");
            return (Criteria) this;
        }

        public Criteria andTypeControlNotIn(List<String> values) {
            addCriterion("type_control not in", values, "typeControl");
            return (Criteria) this;
        }

        public Criteria andTypeControlBetween(String value1, String value2) {
            addCriterion("type_control between", value1, value2, "typeControl");
            return (Criteria) this;
        }

        public Criteria andTypeControlNotBetween(String value1, String value2) {
            addCriterion("type_control not between", value1, value2, "typeControl");
            return (Criteria) this;
        }

        public Criteria andBatchControlIsNull() {
            addCriterion("batch_control is null");
            return (Criteria) this;
        }

        public Criteria andBatchControlIsNotNull() {
            addCriterion("batch_control is not null");
            return (Criteria) this;
        }

        public Criteria andBatchControlEqualTo(String value) {
            addCriterion("batch_control =", value, "batchControl");
            return (Criteria) this;
        }

        public Criteria andBatchControlNotEqualTo(String value) {
            addCriterion("batch_control <>", value, "batchControl");
            return (Criteria) this;
        }

        public Criteria andBatchControlGreaterThan(String value) {
            addCriterion("batch_control >", value, "batchControl");
            return (Criteria) this;
        }

        public Criteria andBatchControlGreaterThanOrEqualTo(String value) {
            addCriterion("batch_control >=", value, "batchControl");
            return (Criteria) this;
        }

        public Criteria andBatchControlLessThan(String value) {
            addCriterion("batch_control <", value, "batchControl");
            return (Criteria) this;
        }

        public Criteria andBatchControlLessThanOrEqualTo(String value) {
            addCriterion("batch_control <=", value, "batchControl");
            return (Criteria) this;
        }

        public Criteria andBatchControlLike(String value) {
            addCriterion("batch_control like", value, "batchControl");
            return (Criteria) this;
        }

        public Criteria andBatchControlNotLike(String value) {
            addCriterion("batch_control not like", value, "batchControl");
            return (Criteria) this;
        }

        public Criteria andBatchControlIn(List<String> values) {
            addCriterion("batch_control in", values, "batchControl");
            return (Criteria) this;
        }

        public Criteria andBatchControlNotIn(List<String> values) {
            addCriterion("batch_control not in", values, "batchControl");
            return (Criteria) this;
        }

        public Criteria andBatchControlBetween(String value1, String value2) {
            addCriterion("batch_control between", value1, value2, "batchControl");
            return (Criteria) this;
        }

        public Criteria andBatchControlNotBetween(String value1, String value2) {
            addCriterion("batch_control not between", value1, value2, "batchControl");
            return (Criteria) this;
        }

        public Criteria andLocalBatchNameIsNull() {
            addCriterion("local_batch_name is null");
            return (Criteria) this;
        }

        public Criteria andLocalBatchNameIsNotNull() {
            addCriterion("local_batch_name is not null");
            return (Criteria) this;
        }

        public Criteria andLocalBatchNameEqualTo(String value) {
            addCriterion("local_batch_name =", value, "localBatchName");
            return (Criteria) this;
        }

        public Criteria andLocalBatchNameNotEqualTo(String value) {
            addCriterion("local_batch_name <>", value, "localBatchName");
            return (Criteria) this;
        }

        public Criteria andLocalBatchNameGreaterThan(String value) {
            addCriterion("local_batch_name >", value, "localBatchName");
            return (Criteria) this;
        }

        public Criteria andLocalBatchNameGreaterThanOrEqualTo(String value) {
            addCriterion("local_batch_name >=", value, "localBatchName");
            return (Criteria) this;
        }

        public Criteria andLocalBatchNameLessThan(String value) {
            addCriterion("local_batch_name <", value, "localBatchName");
            return (Criteria) this;
        }

        public Criteria andLocalBatchNameLessThanOrEqualTo(String value) {
            addCriterion("local_batch_name <=", value, "localBatchName");
            return (Criteria) this;
        }

        public Criteria andLocalBatchNameLike(String value) {
            addCriterion("local_batch_name like", value, "localBatchName");
            return (Criteria) this;
        }

        public Criteria andLocalBatchNameNotLike(String value) {
            addCriterion("local_batch_name not like", value, "localBatchName");
            return (Criteria) this;
        }

        public Criteria andLocalBatchNameIn(List<String> values) {
            addCriterion("local_batch_name in", values, "localBatchName");
            return (Criteria) this;
        }

        public Criteria andLocalBatchNameNotIn(List<String> values) {
            addCriterion("local_batch_name not in", values, "localBatchName");
            return (Criteria) this;
        }

        public Criteria andLocalBatchNameBetween(String value1, String value2) {
            addCriterion("local_batch_name between", value1, value2, "localBatchName");
            return (Criteria) this;
        }

        public Criteria andLocalBatchNameNotBetween(String value1, String value2) {
            addCriterion("local_batch_name not between", value1, value2, "localBatchName");
            return (Criteria) this;
        }

        public Criteria andZslxNameIsNull() {
            addCriterion("zslx_name is null");
            return (Criteria) this;
        }

        public Criteria andZslxNameIsNotNull() {
            addCriterion("zslx_name is not null");
            return (Criteria) this;
        }

        public Criteria andZslxNameEqualTo(String value) {
            addCriterion("zslx_name =", value, "zslxName");
            return (Criteria) this;
        }

        public Criteria andZslxNameNotEqualTo(String value) {
            addCriterion("zslx_name <>", value, "zslxName");
            return (Criteria) this;
        }

        public Criteria andZslxNameGreaterThan(String value) {
            addCriterion("zslx_name >", value, "zslxName");
            return (Criteria) this;
        }

        public Criteria andZslxNameGreaterThanOrEqualTo(String value) {
            addCriterion("zslx_name >=", value, "zslxName");
            return (Criteria) this;
        }

        public Criteria andZslxNameLessThan(String value) {
            addCriterion("zslx_name <", value, "zslxName");
            return (Criteria) this;
        }

        public Criteria andZslxNameLessThanOrEqualTo(String value) {
            addCriterion("zslx_name <=", value, "zslxName");
            return (Criteria) this;
        }

        public Criteria andZslxNameLike(String value) {
            addCriterion("zslx_name like", value, "zslxName");
            return (Criteria) this;
        }

        public Criteria andZslxNameNotLike(String value) {
            addCriterion("zslx_name not like", value, "zslxName");
            return (Criteria) this;
        }

        public Criteria andZslxNameIn(List<String> values) {
            addCriterion("zslx_name in", values, "zslxName");
            return (Criteria) this;
        }

        public Criteria andZslxNameNotIn(List<String> values) {
            addCriterion("zslx_name not in", values, "zslxName");
            return (Criteria) this;
        }

        public Criteria andZslxNameBetween(String value1, String value2) {
            addCriterion("zslx_name between", value1, value2, "zslxName");
            return (Criteria) this;
        }

        public Criteria andZslxNameNotBetween(String value1, String value2) {
            addCriterion("zslx_name not between", value1, value2, "zslxName");
            return (Criteria) this;
        }

        public Criteria andXclevelNameIsNull() {
            addCriterion("xclevel_name is null");
            return (Criteria) this;
        }

        public Criteria andXclevelNameIsNotNull() {
            addCriterion("xclevel_name is not null");
            return (Criteria) this;
        }

        public Criteria andXclevelNameEqualTo(String value) {
            addCriterion("xclevel_name =", value, "xclevelName");
            return (Criteria) this;
        }

        public Criteria andXclevelNameNotEqualTo(String value) {
            addCriterion("xclevel_name <>", value, "xclevelName");
            return (Criteria) this;
        }

        public Criteria andXclevelNameGreaterThan(String value) {
            addCriterion("xclevel_name >", value, "xclevelName");
            return (Criteria) this;
        }

        public Criteria andXclevelNameGreaterThanOrEqualTo(String value) {
            addCriterion("xclevel_name >=", value, "xclevelName");
            return (Criteria) this;
        }

        public Criteria andXclevelNameLessThan(String value) {
            addCriterion("xclevel_name <", value, "xclevelName");
            return (Criteria) this;
        }

        public Criteria andXclevelNameLessThanOrEqualTo(String value) {
            addCriterion("xclevel_name <=", value, "xclevelName");
            return (Criteria) this;
        }

        public Criteria andXclevelNameLike(String value) {
            addCriterion("xclevel_name like", value, "xclevelName");
            return (Criteria) this;
        }

        public Criteria andXclevelNameNotLike(String value) {
            addCriterion("xclevel_name not like", value, "xclevelName");
            return (Criteria) this;
        }

        public Criteria andXclevelNameIn(List<String> values) {
            addCriterion("xclevel_name in", values, "xclevelName");
            return (Criteria) this;
        }

        public Criteria andXclevelNameNotIn(List<String> values) {
            addCriterion("xclevel_name not in", values, "xclevelName");
            return (Criteria) this;
        }

        public Criteria andXclevelNameBetween(String value1, String value2) {
            addCriterion("xclevel_name between", value1, value2, "xclevelName");
            return (Criteria) this;
        }

        public Criteria andXclevelNameNotBetween(String value1, String value2) {
            addCriterion("xclevel_name not between", value1, value2, "xclevelName");
            return (Criteria) this;
        }

        public Criteria andProscoreIsNull() {
            addCriterion("proscore is null");
            return (Criteria) this;
        }

        public Criteria andProscoreIsNotNull() {
            addCriterion("proscore is not null");
            return (Criteria) this;
        }

        public Criteria andProscoreEqualTo(Double value) {
            addCriterion("proscore =", value, "proscore");
            return (Criteria) this;
        }

        public Criteria andProscoreNotEqualTo(Double value) {
            addCriterion("proscore <>", value, "proscore");
            return (Criteria) this;
        }

        public Criteria andProscoreGreaterThan(Double value) {
            addCriterion("proscore >", value, "proscore");
            return (Criteria) this;
        }

        public Criteria andProscoreGreaterThanOrEqualTo(Double value) {
            addCriterion("proscore >=", value, "proscore");
            return (Criteria) this;
        }

        public Criteria andProscoreLessThan(Double value) {
            addCriterion("proscore <", value, "proscore");
            return (Criteria) this;
        }

        public Criteria andProscoreLessThanOrEqualTo(Double value) {
            addCriterion("proscore <=", value, "proscore");
            return (Criteria) this;
        }

        public Criteria andProscoreIn(List<Double> values) {
            addCriterion("proscore in", values, "proscore");
            return (Criteria) this;
        }

        public Criteria andProscoreNotIn(List<Double> values) {
            addCriterion("proscore not in", values, "proscore");
            return (Criteria) this;
        }

        public Criteria andProscoreBetween(Double value1, Double value2) {
            addCriterion("proscore between", value1, value2, "proscore");
            return (Criteria) this;
        }

        public Criteria andProscoreNotBetween(Double value1, Double value2) {
            addCriterion("proscore not between", value1, value2, "proscore");
            return (Criteria) this;
        }

        public Criteria andYearIsNull() {
            addCriterion("year is null");
            return (Criteria) this;
        }

        public Criteria andYearIsNotNull() {
            addCriterion("year is not null");
            return (Criteria) this;
        }

        public Criteria andYearEqualTo(Integer value) {
            addCriterion("year =", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearNotEqualTo(Integer value) {
            addCriterion("year <>", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearGreaterThan(Integer value) {
            addCriterion("year >", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearGreaterThanOrEqualTo(Integer value) {
            addCriterion("year >=", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearLessThan(Integer value) {
            addCriterion("year <", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearLessThanOrEqualTo(Integer value) {
            addCriterion("year <=", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearIn(List<Integer> values) {
            addCriterion("year in", values, "year");
            return (Criteria) this;
        }

        public Criteria andYearNotIn(List<Integer> values) {
            addCriterion("year not in", values, "year");
            return (Criteria) this;
        }

        public Criteria andYearBetween(Integer value1, Integer value2) {
            addCriterion("year between", value1, value2, "year");
            return (Criteria) this;
        }

        public Criteria andYearNotBetween(Integer value1, Integer value2) {
            addCriterion("year not between", value1, value2, "year");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table provincial_score
     *
     * @mbg.generated do_not_delete_during_merge Wed Jul 29 12:05:04 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table provincial_score
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}