package com.lexiangmiao.sample.mybatis.domain.cee;

import java.util.ArrayList;
import java.util.List;

public class SchoolInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table school_info
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table school_info
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table school_info
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_info
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public SchoolInfoExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_info
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_info
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_info
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_info
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_info
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_info
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_info
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_info
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_info
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_info
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table school_info
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSchoolInfoIdIsNull() {
            addCriterion("school_info_id is null");
            return (Criteria) this;
        }

        public Criteria andSchoolInfoIdIsNotNull() {
            addCriterion("school_info_id is not null");
            return (Criteria) this;
        }

        public Criteria andSchoolInfoIdEqualTo(Long value) {
            addCriterion("school_info_id =", value, "schoolInfoId");
            return (Criteria) this;
        }

        public Criteria andSchoolInfoIdNotEqualTo(Long value) {
            addCriterion("school_info_id <>", value, "schoolInfoId");
            return (Criteria) this;
        }

        public Criteria andSchoolInfoIdGreaterThan(Long value) {
            addCriterion("school_info_id >", value, "schoolInfoId");
            return (Criteria) this;
        }

        public Criteria andSchoolInfoIdGreaterThanOrEqualTo(Long value) {
            addCriterion("school_info_id >=", value, "schoolInfoId");
            return (Criteria) this;
        }

        public Criteria andSchoolInfoIdLessThan(Long value) {
            addCriterion("school_info_id <", value, "schoolInfoId");
            return (Criteria) this;
        }

        public Criteria andSchoolInfoIdLessThanOrEqualTo(Long value) {
            addCriterion("school_info_id <=", value, "schoolInfoId");
            return (Criteria) this;
        }

        public Criteria andSchoolInfoIdIn(List<Long> values) {
            addCriterion("school_info_id in", values, "schoolInfoId");
            return (Criteria) this;
        }

        public Criteria andSchoolInfoIdNotIn(List<Long> values) {
            addCriterion("school_info_id not in", values, "schoolInfoId");
            return (Criteria) this;
        }

        public Criteria andSchoolInfoIdBetween(Long value1, Long value2) {
            addCriterion("school_info_id between", value1, value2, "schoolInfoId");
            return (Criteria) this;
        }

        public Criteria andSchoolInfoIdNotBetween(Long value1, Long value2) {
            addCriterion("school_info_id not between", value1, value2, "schoolInfoId");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("address is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("address is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("address =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("address <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("address >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("address >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("address <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("address <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("address like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("address not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("address in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("address not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("address between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("address not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAdmissionsIsNull() {
            addCriterion("admissions is null");
            return (Criteria) this;
        }

        public Criteria andAdmissionsIsNotNull() {
            addCriterion("admissions is not null");
            return (Criteria) this;
        }

        public Criteria andAdmissionsEqualTo(Integer value) {
            addCriterion("admissions =", value, "admissions");
            return (Criteria) this;
        }

        public Criteria andAdmissionsNotEqualTo(Integer value) {
            addCriterion("admissions <>", value, "admissions");
            return (Criteria) this;
        }

        public Criteria andAdmissionsGreaterThan(Integer value) {
            addCriterion("admissions >", value, "admissions");
            return (Criteria) this;
        }

        public Criteria andAdmissionsGreaterThanOrEqualTo(Integer value) {
            addCriterion("admissions >=", value, "admissions");
            return (Criteria) this;
        }

        public Criteria andAdmissionsLessThan(Integer value) {
            addCriterion("admissions <", value, "admissions");
            return (Criteria) this;
        }

        public Criteria andAdmissionsLessThanOrEqualTo(Integer value) {
            addCriterion("admissions <=", value, "admissions");
            return (Criteria) this;
        }

        public Criteria andAdmissionsIn(List<Integer> values) {
            addCriterion("admissions in", values, "admissions");
            return (Criteria) this;
        }

        public Criteria andAdmissionsNotIn(List<Integer> values) {
            addCriterion("admissions not in", values, "admissions");
            return (Criteria) this;
        }

        public Criteria andAdmissionsBetween(Integer value1, Integer value2) {
            addCriterion("admissions between", value1, value2, "admissions");
            return (Criteria) this;
        }

        public Criteria andAdmissionsNotBetween(Integer value1, Integer value2) {
            addCriterion("admissions not between", value1, value2, "admissions");
            return (Criteria) this;
        }

        public Criteria andAnswerurlIsNull() {
            addCriterion("answerurl is null");
            return (Criteria) this;
        }

        public Criteria andAnswerurlIsNotNull() {
            addCriterion("answerurl is not null");
            return (Criteria) this;
        }

        public Criteria andAnswerurlEqualTo(String value) {
            addCriterion("answerurl =", value, "answerurl");
            return (Criteria) this;
        }

        public Criteria andAnswerurlNotEqualTo(String value) {
            addCriterion("answerurl <>", value, "answerurl");
            return (Criteria) this;
        }

        public Criteria andAnswerurlGreaterThan(String value) {
            addCriterion("answerurl >", value, "answerurl");
            return (Criteria) this;
        }

        public Criteria andAnswerurlGreaterThanOrEqualTo(String value) {
            addCriterion("answerurl >=", value, "answerurl");
            return (Criteria) this;
        }

        public Criteria andAnswerurlLessThan(String value) {
            addCriterion("answerurl <", value, "answerurl");
            return (Criteria) this;
        }

        public Criteria andAnswerurlLessThanOrEqualTo(String value) {
            addCriterion("answerurl <=", value, "answerurl");
            return (Criteria) this;
        }

        public Criteria andAnswerurlLike(String value) {
            addCriterion("answerurl like", value, "answerurl");
            return (Criteria) this;
        }

        public Criteria andAnswerurlNotLike(String value) {
            addCriterion("answerurl not like", value, "answerurl");
            return (Criteria) this;
        }

        public Criteria andAnswerurlIn(List<String> values) {
            addCriterion("answerurl in", values, "answerurl");
            return (Criteria) this;
        }

        public Criteria andAnswerurlNotIn(List<String> values) {
            addCriterion("answerurl not in", values, "answerurl");
            return (Criteria) this;
        }

        public Criteria andAnswerurlBetween(String value1, String value2) {
            addCriterion("answerurl between", value1, value2, "answerurl");
            return (Criteria) this;
        }

        public Criteria andAnswerurlNotBetween(String value1, String value2) {
            addCriterion("answerurl not between", value1, value2, "answerurl");
            return (Criteria) this;
        }

        public Criteria andBelongIsNull() {
            addCriterion("belong is null");
            return (Criteria) this;
        }

        public Criteria andBelongIsNotNull() {
            addCriterion("belong is not null");
            return (Criteria) this;
        }

        public Criteria andBelongEqualTo(String value) {
            addCriterion("belong =", value, "belong");
            return (Criteria) this;
        }

        public Criteria andBelongNotEqualTo(String value) {
            addCriterion("belong <>", value, "belong");
            return (Criteria) this;
        }

        public Criteria andBelongGreaterThan(String value) {
            addCriterion("belong >", value, "belong");
            return (Criteria) this;
        }

        public Criteria andBelongGreaterThanOrEqualTo(String value) {
            addCriterion("belong >=", value, "belong");
            return (Criteria) this;
        }

        public Criteria andBelongLessThan(String value) {
            addCriterion("belong <", value, "belong");
            return (Criteria) this;
        }

        public Criteria andBelongLessThanOrEqualTo(String value) {
            addCriterion("belong <=", value, "belong");
            return (Criteria) this;
        }

        public Criteria andBelongLike(String value) {
            addCriterion("belong like", value, "belong");
            return (Criteria) this;
        }

        public Criteria andBelongNotLike(String value) {
            addCriterion("belong not like", value, "belong");
            return (Criteria) this;
        }

        public Criteria andBelongIn(List<String> values) {
            addCriterion("belong in", values, "belong");
            return (Criteria) this;
        }

        public Criteria andBelongNotIn(List<String> values) {
            addCriterion("belong not in", values, "belong");
            return (Criteria) this;
        }

        public Criteria andBelongBetween(String value1, String value2) {
            addCriterion("belong between", value1, value2, "belong");
            return (Criteria) this;
        }

        public Criteria andBelongNotBetween(String value1, String value2) {
            addCriterion("belong not between", value1, value2, "belong");
            return (Criteria) this;
        }

        public Criteria andCentralIsNull() {
            addCriterion("central is null");
            return (Criteria) this;
        }

        public Criteria andCentralIsNotNull() {
            addCriterion("central is not null");
            return (Criteria) this;
        }

        public Criteria andCentralEqualTo(Integer value) {
            addCriterion("central =", value, "central");
            return (Criteria) this;
        }

        public Criteria andCentralNotEqualTo(Integer value) {
            addCriterion("central <>", value, "central");
            return (Criteria) this;
        }

        public Criteria andCentralGreaterThan(Integer value) {
            addCriterion("central >", value, "central");
            return (Criteria) this;
        }

        public Criteria andCentralGreaterThanOrEqualTo(Integer value) {
            addCriterion("central >=", value, "central");
            return (Criteria) this;
        }

        public Criteria andCentralLessThan(Integer value) {
            addCriterion("central <", value, "central");
            return (Criteria) this;
        }

        public Criteria andCentralLessThanOrEqualTo(Integer value) {
            addCriterion("central <=", value, "central");
            return (Criteria) this;
        }

        public Criteria andCentralIn(List<Integer> values) {
            addCriterion("central in", values, "central");
            return (Criteria) this;
        }

        public Criteria andCentralNotIn(List<Integer> values) {
            addCriterion("central not in", values, "central");
            return (Criteria) this;
        }

        public Criteria andCentralBetween(Integer value1, Integer value2) {
            addCriterion("central between", value1, value2, "central");
            return (Criteria) this;
        }

        public Criteria andCentralNotBetween(Integer value1, Integer value2) {
            addCriterion("central not between", value1, value2, "central");
            return (Criteria) this;
        }

        public Criteria andCityIdIsNull() {
            addCriterion("city_id is null");
            return (Criteria) this;
        }

        public Criteria andCityIdIsNotNull() {
            addCriterion("city_id is not null");
            return (Criteria) this;
        }

        public Criteria andCityIdEqualTo(Integer value) {
            addCriterion("city_id =", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdNotEqualTo(Integer value) {
            addCriterion("city_id <>", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdGreaterThan(Integer value) {
            addCriterion("city_id >", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("city_id >=", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdLessThan(Integer value) {
            addCriterion("city_id <", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdLessThanOrEqualTo(Integer value) {
            addCriterion("city_id <=", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdIn(List<Integer> values) {
            addCriterion("city_id in", values, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdNotIn(List<Integer> values) {
            addCriterion("city_id not in", values, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdBetween(Integer value1, Integer value2) {
            addCriterion("city_id between", value1, value2, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdNotBetween(Integer value1, Integer value2) {
            addCriterion("city_id not between", value1, value2, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityNameIsNull() {
            addCriterion("city_name is null");
            return (Criteria) this;
        }

        public Criteria andCityNameIsNotNull() {
            addCriterion("city_name is not null");
            return (Criteria) this;
        }

        public Criteria andCityNameEqualTo(String value) {
            addCriterion("city_name =", value, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameNotEqualTo(String value) {
            addCriterion("city_name <>", value, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameGreaterThan(String value) {
            addCriterion("city_name >", value, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameGreaterThanOrEqualTo(String value) {
            addCriterion("city_name >=", value, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameLessThan(String value) {
            addCriterion("city_name <", value, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameLessThanOrEqualTo(String value) {
            addCriterion("city_name <=", value, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameLike(String value) {
            addCriterion("city_name like", value, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameNotLike(String value) {
            addCriterion("city_name not like", value, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameIn(List<String> values) {
            addCriterion("city_name in", values, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameNotIn(List<String> values) {
            addCriterion("city_name not in", values, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameBetween(String value1, String value2) {
            addCriterion("city_name between", value1, value2, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameNotBetween(String value1, String value2) {
            addCriterion("city_name not between", value1, value2, "cityName");
            return (Criteria) this;
        }

        public Criteria andCodeEnrollIsNull() {
            addCriterion("code_enroll is null");
            return (Criteria) this;
        }

        public Criteria andCodeEnrollIsNotNull() {
            addCriterion("code_enroll is not null");
            return (Criteria) this;
        }

        public Criteria andCodeEnrollEqualTo(Integer value) {
            addCriterion("code_enroll =", value, "codeEnroll");
            return (Criteria) this;
        }

        public Criteria andCodeEnrollNotEqualTo(Integer value) {
            addCriterion("code_enroll <>", value, "codeEnroll");
            return (Criteria) this;
        }

        public Criteria andCodeEnrollGreaterThan(Integer value) {
            addCriterion("code_enroll >", value, "codeEnroll");
            return (Criteria) this;
        }

        public Criteria andCodeEnrollGreaterThanOrEqualTo(Integer value) {
            addCriterion("code_enroll >=", value, "codeEnroll");
            return (Criteria) this;
        }

        public Criteria andCodeEnrollLessThan(Integer value) {
            addCriterion("code_enroll <", value, "codeEnroll");
            return (Criteria) this;
        }

        public Criteria andCodeEnrollLessThanOrEqualTo(Integer value) {
            addCriterion("code_enroll <=", value, "codeEnroll");
            return (Criteria) this;
        }

        public Criteria andCodeEnrollIn(List<Integer> values) {
            addCriterion("code_enroll in", values, "codeEnroll");
            return (Criteria) this;
        }

        public Criteria andCodeEnrollNotIn(List<Integer> values) {
            addCriterion("code_enroll not in", values, "codeEnroll");
            return (Criteria) this;
        }

        public Criteria andCodeEnrollBetween(Integer value1, Integer value2) {
            addCriterion("code_enroll between", value1, value2, "codeEnroll");
            return (Criteria) this;
        }

        public Criteria andCodeEnrollNotBetween(Integer value1, Integer value2) {
            addCriterion("code_enroll not between", value1, value2, "codeEnroll");
            return (Criteria) this;
        }

        public Criteria andCollegesLevelIsNull() {
            addCriterion("colleges_level is null");
            return (Criteria) this;
        }

        public Criteria andCollegesLevelIsNotNull() {
            addCriterion("colleges_level is not null");
            return (Criteria) this;
        }

        public Criteria andCollegesLevelEqualTo(String value) {
            addCriterion("colleges_level =", value, "collegesLevel");
            return (Criteria) this;
        }

        public Criteria andCollegesLevelNotEqualTo(String value) {
            addCriterion("colleges_level <>", value, "collegesLevel");
            return (Criteria) this;
        }

        public Criteria andCollegesLevelGreaterThan(String value) {
            addCriterion("colleges_level >", value, "collegesLevel");
            return (Criteria) this;
        }

        public Criteria andCollegesLevelGreaterThanOrEqualTo(String value) {
            addCriterion("colleges_level >=", value, "collegesLevel");
            return (Criteria) this;
        }

        public Criteria andCollegesLevelLessThan(String value) {
            addCriterion("colleges_level <", value, "collegesLevel");
            return (Criteria) this;
        }

        public Criteria andCollegesLevelLessThanOrEqualTo(String value) {
            addCriterion("colleges_level <=", value, "collegesLevel");
            return (Criteria) this;
        }

        public Criteria andCollegesLevelLike(String value) {
            addCriterion("colleges_level like", value, "collegesLevel");
            return (Criteria) this;
        }

        public Criteria andCollegesLevelNotLike(String value) {
            addCriterion("colleges_level not like", value, "collegesLevel");
            return (Criteria) this;
        }

        public Criteria andCollegesLevelIn(List<String> values) {
            addCriterion("colleges_level in", values, "collegesLevel");
            return (Criteria) this;
        }

        public Criteria andCollegesLevelNotIn(List<String> values) {
            addCriterion("colleges_level not in", values, "collegesLevel");
            return (Criteria) this;
        }

        public Criteria andCollegesLevelBetween(String value1, String value2) {
            addCriterion("colleges_level between", value1, value2, "collegesLevel");
            return (Criteria) this;
        }

        public Criteria andCollegesLevelNotBetween(String value1, String value2) {
            addCriterion("colleges_level not between", value1, value2, "collegesLevel");
            return (Criteria) this;
        }

        public Criteria andCountyIdIsNull() {
            addCriterion("county_id is null");
            return (Criteria) this;
        }

        public Criteria andCountyIdIsNotNull() {
            addCriterion("county_id is not null");
            return (Criteria) this;
        }

        public Criteria andCountyIdEqualTo(Integer value) {
            addCriterion("county_id =", value, "countyId");
            return (Criteria) this;
        }

        public Criteria andCountyIdNotEqualTo(Integer value) {
            addCriterion("county_id <>", value, "countyId");
            return (Criteria) this;
        }

        public Criteria andCountyIdGreaterThan(Integer value) {
            addCriterion("county_id >", value, "countyId");
            return (Criteria) this;
        }

        public Criteria andCountyIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("county_id >=", value, "countyId");
            return (Criteria) this;
        }

        public Criteria andCountyIdLessThan(Integer value) {
            addCriterion("county_id <", value, "countyId");
            return (Criteria) this;
        }

        public Criteria andCountyIdLessThanOrEqualTo(Integer value) {
            addCriterion("county_id <=", value, "countyId");
            return (Criteria) this;
        }

        public Criteria andCountyIdIn(List<Integer> values) {
            addCriterion("county_id in", values, "countyId");
            return (Criteria) this;
        }

        public Criteria andCountyIdNotIn(List<Integer> values) {
            addCriterion("county_id not in", values, "countyId");
            return (Criteria) this;
        }

        public Criteria andCountyIdBetween(Integer value1, Integer value2) {
            addCriterion("county_id between", value1, value2, "countyId");
            return (Criteria) this;
        }

        public Criteria andCountyIdNotBetween(Integer value1, Integer value2) {
            addCriterion("county_id not between", value1, value2, "countyId");
            return (Criteria) this;
        }

        public Criteria andCountyNameIsNull() {
            addCriterion("county_name is null");
            return (Criteria) this;
        }

        public Criteria andCountyNameIsNotNull() {
            addCriterion("county_name is not null");
            return (Criteria) this;
        }

        public Criteria andCountyNameEqualTo(String value) {
            addCriterion("county_name =", value, "countyName");
            return (Criteria) this;
        }

        public Criteria andCountyNameNotEqualTo(String value) {
            addCriterion("county_name <>", value, "countyName");
            return (Criteria) this;
        }

        public Criteria andCountyNameGreaterThan(String value) {
            addCriterion("county_name >", value, "countyName");
            return (Criteria) this;
        }

        public Criteria andCountyNameGreaterThanOrEqualTo(String value) {
            addCriterion("county_name >=", value, "countyName");
            return (Criteria) this;
        }

        public Criteria andCountyNameLessThan(String value) {
            addCriterion("county_name <", value, "countyName");
            return (Criteria) this;
        }

        public Criteria andCountyNameLessThanOrEqualTo(String value) {
            addCriterion("county_name <=", value, "countyName");
            return (Criteria) this;
        }

        public Criteria andCountyNameLike(String value) {
            addCriterion("county_name like", value, "countyName");
            return (Criteria) this;
        }

        public Criteria andCountyNameNotLike(String value) {
            addCriterion("county_name not like", value, "countyName");
            return (Criteria) this;
        }

        public Criteria andCountyNameIn(List<String> values) {
            addCriterion("county_name in", values, "countyName");
            return (Criteria) this;
        }

        public Criteria andCountyNameNotIn(List<String> values) {
            addCriterion("county_name not in", values, "countyName");
            return (Criteria) this;
        }

        public Criteria andCountyNameBetween(String value1, String value2) {
            addCriterion("county_name between", value1, value2, "countyName");
            return (Criteria) this;
        }

        public Criteria andCountyNameNotBetween(String value1, String value2) {
            addCriterion("county_name not between", value1, value2, "countyName");
            return (Criteria) this;
        }

        public Criteria andDepartmentIsNull() {
            addCriterion("department is null");
            return (Criteria) this;
        }

        public Criteria andDepartmentIsNotNull() {
            addCriterion("department is not null");
            return (Criteria) this;
        }

        public Criteria andDepartmentEqualTo(Integer value) {
            addCriterion("department =", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentNotEqualTo(Integer value) {
            addCriterion("department <>", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentGreaterThan(Integer value) {
            addCriterion("department >", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentGreaterThanOrEqualTo(Integer value) {
            addCriterion("department >=", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentLessThan(Integer value) {
            addCriterion("department <", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentLessThanOrEqualTo(Integer value) {
            addCriterion("department <=", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentIn(List<Integer> values) {
            addCriterion("department in", values, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentNotIn(List<Integer> values) {
            addCriterion("department not in", values, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentBetween(Integer value1, Integer value2) {
            addCriterion("department between", value1, value2, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentNotBetween(Integer value1, Integer value2) {
            addCriterion("department not between", value1, value2, "department");
            return (Criteria) this;
        }

        public Criteria andDoublehighIsNull() {
            addCriterion("doublehigh is null");
            return (Criteria) this;
        }

        public Criteria andDoublehighIsNotNull() {
            addCriterion("doublehigh is not null");
            return (Criteria) this;
        }

        public Criteria andDoublehighEqualTo(Integer value) {
            addCriterion("doublehigh =", value, "doublehigh");
            return (Criteria) this;
        }

        public Criteria andDoublehighNotEqualTo(Integer value) {
            addCriterion("doublehigh <>", value, "doublehigh");
            return (Criteria) this;
        }

        public Criteria andDoublehighGreaterThan(Integer value) {
            addCriterion("doublehigh >", value, "doublehigh");
            return (Criteria) this;
        }

        public Criteria andDoublehighGreaterThanOrEqualTo(Integer value) {
            addCriterion("doublehigh >=", value, "doublehigh");
            return (Criteria) this;
        }

        public Criteria andDoublehighLessThan(Integer value) {
            addCriterion("doublehigh <", value, "doublehigh");
            return (Criteria) this;
        }

        public Criteria andDoublehighLessThanOrEqualTo(Integer value) {
            addCriterion("doublehigh <=", value, "doublehigh");
            return (Criteria) this;
        }

        public Criteria andDoublehighIn(List<Integer> values) {
            addCriterion("doublehigh in", values, "doublehigh");
            return (Criteria) this;
        }

        public Criteria andDoublehighNotIn(List<Integer> values) {
            addCriterion("doublehigh not in", values, "doublehigh");
            return (Criteria) this;
        }

        public Criteria andDoublehighBetween(Integer value1, Integer value2) {
            addCriterion("doublehigh between", value1, value2, "doublehigh");
            return (Criteria) this;
        }

        public Criteria andDoublehighNotBetween(Integer value1, Integer value2) {
            addCriterion("doublehigh not between", value1, value2, "doublehigh");
            return (Criteria) this;
        }

        public Criteria andDualClassIsNull() {
            addCriterion("dual_class is null");
            return (Criteria) this;
        }

        public Criteria andDualClassIsNotNull() {
            addCriterion("dual_class is not null");
            return (Criteria) this;
        }

        public Criteria andDualClassEqualTo(Integer value) {
            addCriterion("dual_class =", value, "dualClass");
            return (Criteria) this;
        }

        public Criteria andDualClassNotEqualTo(Integer value) {
            addCriterion("dual_class <>", value, "dualClass");
            return (Criteria) this;
        }

        public Criteria andDualClassGreaterThan(Integer value) {
            addCriterion("dual_class >", value, "dualClass");
            return (Criteria) this;
        }

        public Criteria andDualClassGreaterThanOrEqualTo(Integer value) {
            addCriterion("dual_class >=", value, "dualClass");
            return (Criteria) this;
        }

        public Criteria andDualClassLessThan(Integer value) {
            addCriterion("dual_class <", value, "dualClass");
            return (Criteria) this;
        }

        public Criteria andDualClassLessThanOrEqualTo(Integer value) {
            addCriterion("dual_class <=", value, "dualClass");
            return (Criteria) this;
        }

        public Criteria andDualClassIn(List<Integer> values) {
            addCriterion("dual_class in", values, "dualClass");
            return (Criteria) this;
        }

        public Criteria andDualClassNotIn(List<Integer> values) {
            addCriterion("dual_class not in", values, "dualClass");
            return (Criteria) this;
        }

        public Criteria andDualClassBetween(Integer value1, Integer value2) {
            addCriterion("dual_class between", value1, value2, "dualClass");
            return (Criteria) this;
        }

        public Criteria andDualClassNotBetween(Integer value1, Integer value2) {
            addCriterion("dual_class not between", value1, value2, "dualClass");
            return (Criteria) this;
        }

        public Criteria andDualClassNameIsNull() {
            addCriterion("dual_class_name is null");
            return (Criteria) this;
        }

        public Criteria andDualClassNameIsNotNull() {
            addCriterion("dual_class_name is not null");
            return (Criteria) this;
        }

        public Criteria andDualClassNameEqualTo(String value) {
            addCriterion("dual_class_name =", value, "dualClassName");
            return (Criteria) this;
        }

        public Criteria andDualClassNameNotEqualTo(String value) {
            addCriterion("dual_class_name <>", value, "dualClassName");
            return (Criteria) this;
        }

        public Criteria andDualClassNameGreaterThan(String value) {
            addCriterion("dual_class_name >", value, "dualClassName");
            return (Criteria) this;
        }

        public Criteria andDualClassNameGreaterThanOrEqualTo(String value) {
            addCriterion("dual_class_name >=", value, "dualClassName");
            return (Criteria) this;
        }

        public Criteria andDualClassNameLessThan(String value) {
            addCriterion("dual_class_name <", value, "dualClassName");
            return (Criteria) this;
        }

        public Criteria andDualClassNameLessThanOrEqualTo(String value) {
            addCriterion("dual_class_name <=", value, "dualClassName");
            return (Criteria) this;
        }

        public Criteria andDualClassNameLike(String value) {
            addCriterion("dual_class_name like", value, "dualClassName");
            return (Criteria) this;
        }

        public Criteria andDualClassNameNotLike(String value) {
            addCriterion("dual_class_name not like", value, "dualClassName");
            return (Criteria) this;
        }

        public Criteria andDualClassNameIn(List<String> values) {
            addCriterion("dual_class_name in", values, "dualClassName");
            return (Criteria) this;
        }

        public Criteria andDualClassNameNotIn(List<String> values) {
            addCriterion("dual_class_name not in", values, "dualClassName");
            return (Criteria) this;
        }

        public Criteria andDualClassNameBetween(String value1, String value2) {
            addCriterion("dual_class_name between", value1, value2, "dualClassName");
            return (Criteria) this;
        }

        public Criteria andDualClassNameNotBetween(String value1, String value2) {
            addCriterion("dual_class_name not between", value1, value2, "dualClassName");
            return (Criteria) this;
        }

        public Criteria andF211IsNull() {
            addCriterion("f211 is null");
            return (Criteria) this;
        }

        public Criteria andF211IsNotNull() {
            addCriterion("f211 is not null");
            return (Criteria) this;
        }

        public Criteria andF211EqualTo(Integer value) {
            addCriterion("f211 =", value, "f211");
            return (Criteria) this;
        }

        public Criteria andF211NotEqualTo(Integer value) {
            addCriterion("f211 <>", value, "f211");
            return (Criteria) this;
        }

        public Criteria andF211GreaterThan(Integer value) {
            addCriterion("f211 >", value, "f211");
            return (Criteria) this;
        }

        public Criteria andF211GreaterThanOrEqualTo(Integer value) {
            addCriterion("f211 >=", value, "f211");
            return (Criteria) this;
        }

        public Criteria andF211LessThan(Integer value) {
            addCriterion("f211 <", value, "f211");
            return (Criteria) this;
        }

        public Criteria andF211LessThanOrEqualTo(Integer value) {
            addCriterion("f211 <=", value, "f211");
            return (Criteria) this;
        }

        public Criteria andF211In(List<Integer> values) {
            addCriterion("f211 in", values, "f211");
            return (Criteria) this;
        }

        public Criteria andF211NotIn(List<Integer> values) {
            addCriterion("f211 not in", values, "f211");
            return (Criteria) this;
        }

        public Criteria andF211Between(Integer value1, Integer value2) {
            addCriterion("f211 between", value1, value2, "f211");
            return (Criteria) this;
        }

        public Criteria andF211NotBetween(Integer value1, Integer value2) {
            addCriterion("f211 not between", value1, value2, "f211");
            return (Criteria) this;
        }

        public Criteria andF985IsNull() {
            addCriterion("f985 is null");
            return (Criteria) this;
        }

        public Criteria andF985IsNotNull() {
            addCriterion("f985 is not null");
            return (Criteria) this;
        }

        public Criteria andF985EqualTo(Integer value) {
            addCriterion("f985 =", value, "f985");
            return (Criteria) this;
        }

        public Criteria andF985NotEqualTo(Integer value) {
            addCriterion("f985 <>", value, "f985");
            return (Criteria) this;
        }

        public Criteria andF985GreaterThan(Integer value) {
            addCriterion("f985 >", value, "f985");
            return (Criteria) this;
        }

        public Criteria andF985GreaterThanOrEqualTo(Integer value) {
            addCriterion("f985 >=", value, "f985");
            return (Criteria) this;
        }

        public Criteria andF985LessThan(Integer value) {
            addCriterion("f985 <", value, "f985");
            return (Criteria) this;
        }

        public Criteria andF985LessThanOrEqualTo(Integer value) {
            addCriterion("f985 <=", value, "f985");
            return (Criteria) this;
        }

        public Criteria andF985In(List<Integer> values) {
            addCriterion("f985 in", values, "f985");
            return (Criteria) this;
        }

        public Criteria andF985NotIn(List<Integer> values) {
            addCriterion("f985 not in", values, "f985");
            return (Criteria) this;
        }

        public Criteria andF985Between(Integer value1, Integer value2) {
            addCriterion("f985 between", value1, value2, "f985");
            return (Criteria) this;
        }

        public Criteria andF985NotBetween(Integer value1, Integer value2) {
            addCriterion("f985 not between", value1, value2, "f985");
            return (Criteria) this;
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIsRecruitmentIsNull() {
            addCriterion("is_recruitment is null");
            return (Criteria) this;
        }

        public Criteria andIsRecruitmentIsNotNull() {
            addCriterion("is_recruitment is not null");
            return (Criteria) this;
        }

        public Criteria andIsRecruitmentEqualTo(Integer value) {
            addCriterion("is_recruitment =", value, "isRecruitment");
            return (Criteria) this;
        }

        public Criteria andIsRecruitmentNotEqualTo(Integer value) {
            addCriterion("is_recruitment <>", value, "isRecruitment");
            return (Criteria) this;
        }

        public Criteria andIsRecruitmentGreaterThan(Integer value) {
            addCriterion("is_recruitment >", value, "isRecruitment");
            return (Criteria) this;
        }

        public Criteria andIsRecruitmentGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_recruitment >=", value, "isRecruitment");
            return (Criteria) this;
        }

        public Criteria andIsRecruitmentLessThan(Integer value) {
            addCriterion("is_recruitment <", value, "isRecruitment");
            return (Criteria) this;
        }

        public Criteria andIsRecruitmentLessThanOrEqualTo(Integer value) {
            addCriterion("is_recruitment <=", value, "isRecruitment");
            return (Criteria) this;
        }

        public Criteria andIsRecruitmentIn(List<Integer> values) {
            addCriterion("is_recruitment in", values, "isRecruitment");
            return (Criteria) this;
        }

        public Criteria andIsRecruitmentNotIn(List<Integer> values) {
            addCriterion("is_recruitment not in", values, "isRecruitment");
            return (Criteria) this;
        }

        public Criteria andIsRecruitmentBetween(Integer value1, Integer value2) {
            addCriterion("is_recruitment between", value1, value2, "isRecruitment");
            return (Criteria) this;
        }

        public Criteria andIsRecruitmentNotBetween(Integer value1, Integer value2) {
            addCriterion("is_recruitment not between", value1, value2, "isRecruitment");
            return (Criteria) this;
        }

        public Criteria andIsTopIsNull() {
            addCriterion("is_top is null");
            return (Criteria) this;
        }

        public Criteria andIsTopIsNotNull() {
            addCriterion("is_top is not null");
            return (Criteria) this;
        }

        public Criteria andIsTopEqualTo(Integer value) {
            addCriterion("is_top =", value, "isTop");
            return (Criteria) this;
        }

        public Criteria andIsTopNotEqualTo(Integer value) {
            addCriterion("is_top <>", value, "isTop");
            return (Criteria) this;
        }

        public Criteria andIsTopGreaterThan(Integer value) {
            addCriterion("is_top >", value, "isTop");
            return (Criteria) this;
        }

        public Criteria andIsTopGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_top >=", value, "isTop");
            return (Criteria) this;
        }

        public Criteria andIsTopLessThan(Integer value) {
            addCriterion("is_top <", value, "isTop");
            return (Criteria) this;
        }

        public Criteria andIsTopLessThanOrEqualTo(Integer value) {
            addCriterion("is_top <=", value, "isTop");
            return (Criteria) this;
        }

        public Criteria andIsTopIn(List<Integer> values) {
            addCriterion("is_top in", values, "isTop");
            return (Criteria) this;
        }

        public Criteria andIsTopNotIn(List<Integer> values) {
            addCriterion("is_top not in", values, "isTop");
            return (Criteria) this;
        }

        public Criteria andIsTopBetween(Integer value1, Integer value2) {
            addCriterion("is_top between", value1, value2, "isTop");
            return (Criteria) this;
        }

        public Criteria andIsTopNotBetween(Integer value1, Integer value2) {
            addCriterion("is_top not between", value1, value2, "isTop");
            return (Criteria) this;
        }

        public Criteria andLevelIsNull() {
            addCriterion("level is null");
            return (Criteria) this;
        }

        public Criteria andLevelIsNotNull() {
            addCriterion("level is not null");
            return (Criteria) this;
        }

        public Criteria andLevelEqualTo(Integer value) {
            addCriterion("level =", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotEqualTo(Integer value) {
            addCriterion("level <>", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThan(Integer value) {
            addCriterion("level >", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("level >=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThan(Integer value) {
            addCriterion("level <", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThanOrEqualTo(Integer value) {
            addCriterion("level <=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelIn(List<Integer> values) {
            addCriterion("level in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotIn(List<Integer> values) {
            addCriterion("level not in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelBetween(Integer value1, Integer value2) {
            addCriterion("level between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotBetween(Integer value1, Integer value2) {
            addCriterion("level not between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNameIsNull() {
            addCriterion("level_name is null");
            return (Criteria) this;
        }

        public Criteria andLevelNameIsNotNull() {
            addCriterion("level_name is not null");
            return (Criteria) this;
        }

        public Criteria andLevelNameEqualTo(String value) {
            addCriterion("level_name =", value, "levelName");
            return (Criteria) this;
        }

        public Criteria andLevelNameNotEqualTo(String value) {
            addCriterion("level_name <>", value, "levelName");
            return (Criteria) this;
        }

        public Criteria andLevelNameGreaterThan(String value) {
            addCriterion("level_name >", value, "levelName");
            return (Criteria) this;
        }

        public Criteria andLevelNameGreaterThanOrEqualTo(String value) {
            addCriterion("level_name >=", value, "levelName");
            return (Criteria) this;
        }

        public Criteria andLevelNameLessThan(String value) {
            addCriterion("level_name <", value, "levelName");
            return (Criteria) this;
        }

        public Criteria andLevelNameLessThanOrEqualTo(String value) {
            addCriterion("level_name <=", value, "levelName");
            return (Criteria) this;
        }

        public Criteria andLevelNameLike(String value) {
            addCriterion("level_name like", value, "levelName");
            return (Criteria) this;
        }

        public Criteria andLevelNameNotLike(String value) {
            addCriterion("level_name not like", value, "levelName");
            return (Criteria) this;
        }

        public Criteria andLevelNameIn(List<String> values) {
            addCriterion("level_name in", values, "levelName");
            return (Criteria) this;
        }

        public Criteria andLevelNameNotIn(List<String> values) {
            addCriterion("level_name not in", values, "levelName");
            return (Criteria) this;
        }

        public Criteria andLevelNameBetween(String value1, String value2) {
            addCriterion("level_name between", value1, value2, "levelName");
            return (Criteria) this;
        }

        public Criteria andLevelNameNotBetween(String value1, String value2) {
            addCriterion("level_name not between", value1, value2, "levelName");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNatureIsNull() {
            addCriterion("nature is null");
            return (Criteria) this;
        }

        public Criteria andNatureIsNotNull() {
            addCriterion("nature is not null");
            return (Criteria) this;
        }

        public Criteria andNatureEqualTo(Integer value) {
            addCriterion("nature =", value, "nature");
            return (Criteria) this;
        }

        public Criteria andNatureNotEqualTo(Integer value) {
            addCriterion("nature <>", value, "nature");
            return (Criteria) this;
        }

        public Criteria andNatureGreaterThan(Integer value) {
            addCriterion("nature >", value, "nature");
            return (Criteria) this;
        }

        public Criteria andNatureGreaterThanOrEqualTo(Integer value) {
            addCriterion("nature >=", value, "nature");
            return (Criteria) this;
        }

        public Criteria andNatureLessThan(Integer value) {
            addCriterion("nature <", value, "nature");
            return (Criteria) this;
        }

        public Criteria andNatureLessThanOrEqualTo(Integer value) {
            addCriterion("nature <=", value, "nature");
            return (Criteria) this;
        }

        public Criteria andNatureIn(List<Integer> values) {
            addCriterion("nature in", values, "nature");
            return (Criteria) this;
        }

        public Criteria andNatureNotIn(List<Integer> values) {
            addCriterion("nature not in", values, "nature");
            return (Criteria) this;
        }

        public Criteria andNatureBetween(Integer value1, Integer value2) {
            addCriterion("nature between", value1, value2, "nature");
            return (Criteria) this;
        }

        public Criteria andNatureNotBetween(Integer value1, Integer value2) {
            addCriterion("nature not between", value1, value2, "nature");
            return (Criteria) this;
        }

        public Criteria andNatureNameIsNull() {
            addCriterion("nature_name is null");
            return (Criteria) this;
        }

        public Criteria andNatureNameIsNotNull() {
            addCriterion("nature_name is not null");
            return (Criteria) this;
        }

        public Criteria andNatureNameEqualTo(String value) {
            addCriterion("nature_name =", value, "natureName");
            return (Criteria) this;
        }

        public Criteria andNatureNameNotEqualTo(String value) {
            addCriterion("nature_name <>", value, "natureName");
            return (Criteria) this;
        }

        public Criteria andNatureNameGreaterThan(String value) {
            addCriterion("nature_name >", value, "natureName");
            return (Criteria) this;
        }

        public Criteria andNatureNameGreaterThanOrEqualTo(String value) {
            addCriterion("nature_name >=", value, "natureName");
            return (Criteria) this;
        }

        public Criteria andNatureNameLessThan(String value) {
            addCriterion("nature_name <", value, "natureName");
            return (Criteria) this;
        }

        public Criteria andNatureNameLessThanOrEqualTo(String value) {
            addCriterion("nature_name <=", value, "natureName");
            return (Criteria) this;
        }

        public Criteria andNatureNameLike(String value) {
            addCriterion("nature_name like", value, "natureName");
            return (Criteria) this;
        }

        public Criteria andNatureNameNotLike(String value) {
            addCriterion("nature_name not like", value, "natureName");
            return (Criteria) this;
        }

        public Criteria andNatureNameIn(List<String> values) {
            addCriterion("nature_name in", values, "natureName");
            return (Criteria) this;
        }

        public Criteria andNatureNameNotIn(List<String> values) {
            addCriterion("nature_name not in", values, "natureName");
            return (Criteria) this;
        }

        public Criteria andNatureNameBetween(String value1, String value2) {
            addCriterion("nature_name between", value1, value2, "natureName");
            return (Criteria) this;
        }

        public Criteria andNatureNameNotBetween(String value1, String value2) {
            addCriterion("nature_name not between", value1, value2, "natureName");
            return (Criteria) this;
        }

        public Criteria andProvinceIdIsNull() {
            addCriterion("province_id is null");
            return (Criteria) this;
        }

        public Criteria andProvinceIdIsNotNull() {
            addCriterion("province_id is not null");
            return (Criteria) this;
        }

        public Criteria andProvinceIdEqualTo(Integer value) {
            addCriterion("province_id =", value, "provinceId");
            return (Criteria) this;
        }

        public Criteria andProvinceIdNotEqualTo(Integer value) {
            addCriterion("province_id <>", value, "provinceId");
            return (Criteria) this;
        }

        public Criteria andProvinceIdGreaterThan(Integer value) {
            addCriterion("province_id >", value, "provinceId");
            return (Criteria) this;
        }

        public Criteria andProvinceIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("province_id >=", value, "provinceId");
            return (Criteria) this;
        }

        public Criteria andProvinceIdLessThan(Integer value) {
            addCriterion("province_id <", value, "provinceId");
            return (Criteria) this;
        }

        public Criteria andProvinceIdLessThanOrEqualTo(Integer value) {
            addCriterion("province_id <=", value, "provinceId");
            return (Criteria) this;
        }

        public Criteria andProvinceIdIn(List<Integer> values) {
            addCriterion("province_id in", values, "provinceId");
            return (Criteria) this;
        }

        public Criteria andProvinceIdNotIn(List<Integer> values) {
            addCriterion("province_id not in", values, "provinceId");
            return (Criteria) this;
        }

        public Criteria andProvinceIdBetween(Integer value1, Integer value2) {
            addCriterion("province_id between", value1, value2, "provinceId");
            return (Criteria) this;
        }

        public Criteria andProvinceIdNotBetween(Integer value1, Integer value2) {
            addCriterion("province_id not between", value1, value2, "provinceId");
            return (Criteria) this;
        }

        public Criteria andProvinceNameIsNull() {
            addCriterion("province_name is null");
            return (Criteria) this;
        }

        public Criteria andProvinceNameIsNotNull() {
            addCriterion("province_name is not null");
            return (Criteria) this;
        }

        public Criteria andProvinceNameEqualTo(String value) {
            addCriterion("province_name =", value, "provinceName");
            return (Criteria) this;
        }

        public Criteria andProvinceNameNotEqualTo(String value) {
            addCriterion("province_name <>", value, "provinceName");
            return (Criteria) this;
        }

        public Criteria andProvinceNameGreaterThan(String value) {
            addCriterion("province_name >", value, "provinceName");
            return (Criteria) this;
        }

        public Criteria andProvinceNameGreaterThanOrEqualTo(String value) {
            addCriterion("province_name >=", value, "provinceName");
            return (Criteria) this;
        }

        public Criteria andProvinceNameLessThan(String value) {
            addCriterion("province_name <", value, "provinceName");
            return (Criteria) this;
        }

        public Criteria andProvinceNameLessThanOrEqualTo(String value) {
            addCriterion("province_name <=", value, "provinceName");
            return (Criteria) this;
        }

        public Criteria andProvinceNameLike(String value) {
            addCriterion("province_name like", value, "provinceName");
            return (Criteria) this;
        }

        public Criteria andProvinceNameNotLike(String value) {
            addCriterion("province_name not like", value, "provinceName");
            return (Criteria) this;
        }

        public Criteria andProvinceNameIn(List<String> values) {
            addCriterion("province_name in", values, "provinceName");
            return (Criteria) this;
        }

        public Criteria andProvinceNameNotIn(List<String> values) {
            addCriterion("province_name not in", values, "provinceName");
            return (Criteria) this;
        }

        public Criteria andProvinceNameBetween(String value1, String value2) {
            addCriterion("province_name between", value1, value2, "provinceName");
            return (Criteria) this;
        }

        public Criteria andProvinceNameNotBetween(String value1, String value2) {
            addCriterion("province_name not between", value1, value2, "provinceName");
            return (Criteria) this;
        }

        public Criteria andPublishIdIsNull() {
            addCriterion("publish_id is null");
            return (Criteria) this;
        }

        public Criteria andPublishIdIsNotNull() {
            addCriterion("publish_id is not null");
            return (Criteria) this;
        }

        public Criteria andPublishIdEqualTo(String value) {
            addCriterion("publish_id =", value, "publishId");
            return (Criteria) this;
        }

        public Criteria andPublishIdNotEqualTo(String value) {
            addCriterion("publish_id <>", value, "publishId");
            return (Criteria) this;
        }

        public Criteria andPublishIdGreaterThan(String value) {
            addCriterion("publish_id >", value, "publishId");
            return (Criteria) this;
        }

        public Criteria andPublishIdGreaterThanOrEqualTo(String value) {
            addCriterion("publish_id >=", value, "publishId");
            return (Criteria) this;
        }

        public Criteria andPublishIdLessThan(String value) {
            addCriterion("publish_id <", value, "publishId");
            return (Criteria) this;
        }

        public Criteria andPublishIdLessThanOrEqualTo(String value) {
            addCriterion("publish_id <=", value, "publishId");
            return (Criteria) this;
        }

        public Criteria andPublishIdLike(String value) {
            addCriterion("publish_id like", value, "publishId");
            return (Criteria) this;
        }

        public Criteria andPublishIdNotLike(String value) {
            addCriterion("publish_id not like", value, "publishId");
            return (Criteria) this;
        }

        public Criteria andPublishIdIn(List<String> values) {
            addCriterion("publish_id in", values, "publishId");
            return (Criteria) this;
        }

        public Criteria andPublishIdNotIn(List<String> values) {
            addCriterion("publish_id not in", values, "publishId");
            return (Criteria) this;
        }

        public Criteria andPublishIdBetween(String value1, String value2) {
            addCriterion("publish_id between", value1, value2, "publishId");
            return (Criteria) this;
        }

        public Criteria andPublishIdNotBetween(String value1, String value2) {
            addCriterion("publish_id not between", value1, value2, "publishId");
            return (Criteria) this;
        }

        public Criteria andRankIsNull() {
            addCriterion("rank is null");
            return (Criteria) this;
        }

        public Criteria andRankIsNotNull() {
            addCriterion("rank is not null");
            return (Criteria) this;
        }

        public Criteria andRankEqualTo(Integer value) {
            addCriterion("rank =", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankNotEqualTo(Integer value) {
            addCriterion("rank <>", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankGreaterThan(Integer value) {
            addCriterion("rank >", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankGreaterThanOrEqualTo(Integer value) {
            addCriterion("rank >=", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankLessThan(Integer value) {
            addCriterion("rank <", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankLessThanOrEqualTo(Integer value) {
            addCriterion("rank <=", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankIn(List<Integer> values) {
            addCriterion("rank in", values, "rank");
            return (Criteria) this;
        }

        public Criteria andRankNotIn(List<Integer> values) {
            addCriterion("rank not in", values, "rank");
            return (Criteria) this;
        }

        public Criteria andRankBetween(Integer value1, Integer value2) {
            addCriterion("rank between", value1, value2, "rank");
            return (Criteria) this;
        }

        public Criteria andRankNotBetween(Integer value1, Integer value2) {
            addCriterion("rank not between", value1, value2, "rank");
            return (Criteria) this;
        }

        public Criteria andRankTypeIsNull() {
            addCriterion("rank_type is null");
            return (Criteria) this;
        }

        public Criteria andRankTypeIsNotNull() {
            addCriterion("rank_type is not null");
            return (Criteria) this;
        }

        public Criteria andRankTypeEqualTo(Integer value) {
            addCriterion("rank_type =", value, "rankType");
            return (Criteria) this;
        }

        public Criteria andRankTypeNotEqualTo(Integer value) {
            addCriterion("rank_type <>", value, "rankType");
            return (Criteria) this;
        }

        public Criteria andRankTypeGreaterThan(Integer value) {
            addCriterion("rank_type >", value, "rankType");
            return (Criteria) this;
        }

        public Criteria andRankTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("rank_type >=", value, "rankType");
            return (Criteria) this;
        }

        public Criteria andRankTypeLessThan(Integer value) {
            addCriterion("rank_type <", value, "rankType");
            return (Criteria) this;
        }

        public Criteria andRankTypeLessThanOrEqualTo(Integer value) {
            addCriterion("rank_type <=", value, "rankType");
            return (Criteria) this;
        }

        public Criteria andRankTypeIn(List<Integer> values) {
            addCriterion("rank_type in", values, "rankType");
            return (Criteria) this;
        }

        public Criteria andRankTypeNotIn(List<Integer> values) {
            addCriterion("rank_type not in", values, "rankType");
            return (Criteria) this;
        }

        public Criteria andRankTypeBetween(Integer value1, Integer value2) {
            addCriterion("rank_type between", value1, value2, "rankType");
            return (Criteria) this;
        }

        public Criteria andRankTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("rank_type not between", value1, value2, "rankType");
            return (Criteria) this;
        }

        public Criteria andSchoolIdIsNull() {
            addCriterion("school_id is null");
            return (Criteria) this;
        }

        public Criteria andSchoolIdIsNotNull() {
            addCriterion("school_id is not null");
            return (Criteria) this;
        }

        public Criteria andSchoolIdEqualTo(Integer value) {
            addCriterion("school_id =", value, "schoolId");
            return (Criteria) this;
        }

        public Criteria andSchoolIdNotEqualTo(Integer value) {
            addCriterion("school_id <>", value, "schoolId");
            return (Criteria) this;
        }

        public Criteria andSchoolIdGreaterThan(Integer value) {
            addCriterion("school_id >", value, "schoolId");
            return (Criteria) this;
        }

        public Criteria andSchoolIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("school_id >=", value, "schoolId");
            return (Criteria) this;
        }

        public Criteria andSchoolIdLessThan(Integer value) {
            addCriterion("school_id <", value, "schoolId");
            return (Criteria) this;
        }

        public Criteria andSchoolIdLessThanOrEqualTo(Integer value) {
            addCriterion("school_id <=", value, "schoolId");
            return (Criteria) this;
        }

        public Criteria andSchoolIdIn(List<Integer> values) {
            addCriterion("school_id in", values, "schoolId");
            return (Criteria) this;
        }

        public Criteria andSchoolIdNotIn(List<Integer> values) {
            addCriterion("school_id not in", values, "schoolId");
            return (Criteria) this;
        }

        public Criteria andSchoolIdBetween(Integer value1, Integer value2) {
            addCriterion("school_id between", value1, value2, "schoolId");
            return (Criteria) this;
        }

        public Criteria andSchoolIdNotBetween(Integer value1, Integer value2) {
            addCriterion("school_id not between", value1, value2, "schoolId");
            return (Criteria) this;
        }

        public Criteria andSchoolTypeIsNull() {
            addCriterion("school_type is null");
            return (Criteria) this;
        }

        public Criteria andSchoolTypeIsNotNull() {
            addCriterion("school_type is not null");
            return (Criteria) this;
        }

        public Criteria andSchoolTypeEqualTo(Integer value) {
            addCriterion("school_type =", value, "schoolType");
            return (Criteria) this;
        }

        public Criteria andSchoolTypeNotEqualTo(Integer value) {
            addCriterion("school_type <>", value, "schoolType");
            return (Criteria) this;
        }

        public Criteria andSchoolTypeGreaterThan(Integer value) {
            addCriterion("school_type >", value, "schoolType");
            return (Criteria) this;
        }

        public Criteria andSchoolTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("school_type >=", value, "schoolType");
            return (Criteria) this;
        }

        public Criteria andSchoolTypeLessThan(Integer value) {
            addCriterion("school_type <", value, "schoolType");
            return (Criteria) this;
        }

        public Criteria andSchoolTypeLessThanOrEqualTo(Integer value) {
            addCriterion("school_type <=", value, "schoolType");
            return (Criteria) this;
        }

        public Criteria andSchoolTypeIn(List<Integer> values) {
            addCriterion("school_type in", values, "schoolType");
            return (Criteria) this;
        }

        public Criteria andSchoolTypeNotIn(List<Integer> values) {
            addCriterion("school_type not in", values, "schoolType");
            return (Criteria) this;
        }

        public Criteria andSchoolTypeBetween(Integer value1, Integer value2) {
            addCriterion("school_type between", value1, value2, "schoolType");
            return (Criteria) this;
        }

        public Criteria andSchoolTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("school_type not between", value1, value2, "schoolType");
            return (Criteria) this;
        }

        public Criteria andSingleProvinceIsNull() {
            addCriterion("single_province is null");
            return (Criteria) this;
        }

        public Criteria andSingleProvinceIsNotNull() {
            addCriterion("single_province is not null");
            return (Criteria) this;
        }

        public Criteria andSingleProvinceEqualTo(String value) {
            addCriterion("single_province =", value, "singleProvince");
            return (Criteria) this;
        }

        public Criteria andSingleProvinceNotEqualTo(String value) {
            addCriterion("single_province <>", value, "singleProvince");
            return (Criteria) this;
        }

        public Criteria andSingleProvinceGreaterThan(String value) {
            addCriterion("single_province >", value, "singleProvince");
            return (Criteria) this;
        }

        public Criteria andSingleProvinceGreaterThanOrEqualTo(String value) {
            addCriterion("single_province >=", value, "singleProvince");
            return (Criteria) this;
        }

        public Criteria andSingleProvinceLessThan(String value) {
            addCriterion("single_province <", value, "singleProvince");
            return (Criteria) this;
        }

        public Criteria andSingleProvinceLessThanOrEqualTo(String value) {
            addCriterion("single_province <=", value, "singleProvince");
            return (Criteria) this;
        }

        public Criteria andSingleProvinceLike(String value) {
            addCriterion("single_province like", value, "singleProvince");
            return (Criteria) this;
        }

        public Criteria andSingleProvinceNotLike(String value) {
            addCriterion("single_province not like", value, "singleProvince");
            return (Criteria) this;
        }

        public Criteria andSingleProvinceIn(List<String> values) {
            addCriterion("single_province in", values, "singleProvince");
            return (Criteria) this;
        }

        public Criteria andSingleProvinceNotIn(List<String> values) {
            addCriterion("single_province not in", values, "singleProvince");
            return (Criteria) this;
        }

        public Criteria andSingleProvinceBetween(String value1, String value2) {
            addCriterion("single_province between", value1, value2, "singleProvince");
            return (Criteria) this;
        }

        public Criteria andSingleProvinceNotBetween(String value1, String value2) {
            addCriterion("single_province not between", value1, value2, "singleProvince");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(Integer value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(Integer value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(Integer value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(Integer value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(Integer value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<Integer> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<Integer> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(Integer value1, Integer value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNameIsNull() {
            addCriterion("type_name is null");
            return (Criteria) this;
        }

        public Criteria andTypeNameIsNotNull() {
            addCriterion("type_name is not null");
            return (Criteria) this;
        }

        public Criteria andTypeNameEqualTo(String value) {
            addCriterion("type_name =", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameNotEqualTo(String value) {
            addCriterion("type_name <>", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameGreaterThan(String value) {
            addCriterion("type_name >", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameGreaterThanOrEqualTo(String value) {
            addCriterion("type_name >=", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameLessThan(String value) {
            addCriterion("type_name <", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameLessThanOrEqualTo(String value) {
            addCriterion("type_name <=", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameLike(String value) {
            addCriterion("type_name like", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameNotLike(String value) {
            addCriterion("type_name not like", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameIn(List<String> values) {
            addCriterion("type_name in", values, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameNotIn(List<String> values) {
            addCriterion("type_name not in", values, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameBetween(String value1, String value2) {
            addCriterion("type_name between", value1, value2, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameNotBetween(String value1, String value2) {
            addCriterion("type_name not between", value1, value2, "typeName");
            return (Criteria) this;
        }

        public Criteria andViewMonthIsNull() {
            addCriterion("view_month is null");
            return (Criteria) this;
        }

        public Criteria andViewMonthIsNotNull() {
            addCriterion("view_month is not null");
            return (Criteria) this;
        }

        public Criteria andViewMonthEqualTo(Integer value) {
            addCriterion("view_month =", value, "viewMonth");
            return (Criteria) this;
        }

        public Criteria andViewMonthNotEqualTo(Integer value) {
            addCriterion("view_month <>", value, "viewMonth");
            return (Criteria) this;
        }

        public Criteria andViewMonthGreaterThan(Integer value) {
            addCriterion("view_month >", value, "viewMonth");
            return (Criteria) this;
        }

        public Criteria andViewMonthGreaterThanOrEqualTo(Integer value) {
            addCriterion("view_month >=", value, "viewMonth");
            return (Criteria) this;
        }

        public Criteria andViewMonthLessThan(Integer value) {
            addCriterion("view_month <", value, "viewMonth");
            return (Criteria) this;
        }

        public Criteria andViewMonthLessThanOrEqualTo(Integer value) {
            addCriterion("view_month <=", value, "viewMonth");
            return (Criteria) this;
        }

        public Criteria andViewMonthIn(List<Integer> values) {
            addCriterion("view_month in", values, "viewMonth");
            return (Criteria) this;
        }

        public Criteria andViewMonthNotIn(List<Integer> values) {
            addCriterion("view_month not in", values, "viewMonth");
            return (Criteria) this;
        }

        public Criteria andViewMonthBetween(Integer value1, Integer value2) {
            addCriterion("view_month between", value1, value2, "viewMonth");
            return (Criteria) this;
        }

        public Criteria andViewMonthNotBetween(Integer value1, Integer value2) {
            addCriterion("view_month not between", value1, value2, "viewMonth");
            return (Criteria) this;
        }

        public Criteria andViewTotalIsNull() {
            addCriterion("view_total is null");
            return (Criteria) this;
        }

        public Criteria andViewTotalIsNotNull() {
            addCriterion("view_total is not null");
            return (Criteria) this;
        }

        public Criteria andViewTotalEqualTo(String value) {
            addCriterion("view_total =", value, "viewTotal");
            return (Criteria) this;
        }

        public Criteria andViewTotalNotEqualTo(String value) {
            addCriterion("view_total <>", value, "viewTotal");
            return (Criteria) this;
        }

        public Criteria andViewTotalGreaterThan(String value) {
            addCriterion("view_total >", value, "viewTotal");
            return (Criteria) this;
        }

        public Criteria andViewTotalGreaterThanOrEqualTo(String value) {
            addCriterion("view_total >=", value, "viewTotal");
            return (Criteria) this;
        }

        public Criteria andViewTotalLessThan(String value) {
            addCriterion("view_total <", value, "viewTotal");
            return (Criteria) this;
        }

        public Criteria andViewTotalLessThanOrEqualTo(String value) {
            addCriterion("view_total <=", value, "viewTotal");
            return (Criteria) this;
        }

        public Criteria andViewTotalLike(String value) {
            addCriterion("view_total like", value, "viewTotal");
            return (Criteria) this;
        }

        public Criteria andViewTotalNotLike(String value) {
            addCriterion("view_total not like", value, "viewTotal");
            return (Criteria) this;
        }

        public Criteria andViewTotalIn(List<String> values) {
            addCriterion("view_total in", values, "viewTotal");
            return (Criteria) this;
        }

        public Criteria andViewTotalNotIn(List<String> values) {
            addCriterion("view_total not in", values, "viewTotal");
            return (Criteria) this;
        }

        public Criteria andViewTotalBetween(String value1, String value2) {
            addCriterion("view_total between", value1, value2, "viewTotal");
            return (Criteria) this;
        }

        public Criteria andViewTotalNotBetween(String value1, String value2) {
            addCriterion("view_total not between", value1, value2, "viewTotal");
            return (Criteria) this;
        }

        public Criteria andViewTotalNumberIsNull() {
            addCriterion("view_total_number is null");
            return (Criteria) this;
        }

        public Criteria andViewTotalNumberIsNotNull() {
            addCriterion("view_total_number is not null");
            return (Criteria) this;
        }

        public Criteria andViewTotalNumberEqualTo(Integer value) {
            addCriterion("view_total_number =", value, "viewTotalNumber");
            return (Criteria) this;
        }

        public Criteria andViewTotalNumberNotEqualTo(Integer value) {
            addCriterion("view_total_number <>", value, "viewTotalNumber");
            return (Criteria) this;
        }

        public Criteria andViewTotalNumberGreaterThan(Integer value) {
            addCriterion("view_total_number >", value, "viewTotalNumber");
            return (Criteria) this;
        }

        public Criteria andViewTotalNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("view_total_number >=", value, "viewTotalNumber");
            return (Criteria) this;
        }

        public Criteria andViewTotalNumberLessThan(Integer value) {
            addCriterion("view_total_number <", value, "viewTotalNumber");
            return (Criteria) this;
        }

        public Criteria andViewTotalNumberLessThanOrEqualTo(Integer value) {
            addCriterion("view_total_number <=", value, "viewTotalNumber");
            return (Criteria) this;
        }

        public Criteria andViewTotalNumberIn(List<Integer> values) {
            addCriterion("view_total_number in", values, "viewTotalNumber");
            return (Criteria) this;
        }

        public Criteria andViewTotalNumberNotIn(List<Integer> values) {
            addCriterion("view_total_number not in", values, "viewTotalNumber");
            return (Criteria) this;
        }

        public Criteria andViewTotalNumberBetween(Integer value1, Integer value2) {
            addCriterion("view_total_number between", value1, value2, "viewTotalNumber");
            return (Criteria) this;
        }

        public Criteria andViewTotalNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("view_total_number not between", value1, value2, "viewTotalNumber");
            return (Criteria) this;
        }

        public Criteria andViewWeekIsNull() {
            addCriterion("view_week is null");
            return (Criteria) this;
        }

        public Criteria andViewWeekIsNotNull() {
            addCriterion("view_week is not null");
            return (Criteria) this;
        }

        public Criteria andViewWeekEqualTo(Integer value) {
            addCriterion("view_week =", value, "viewWeek");
            return (Criteria) this;
        }

        public Criteria andViewWeekNotEqualTo(Integer value) {
            addCriterion("view_week <>", value, "viewWeek");
            return (Criteria) this;
        }

        public Criteria andViewWeekGreaterThan(Integer value) {
            addCriterion("view_week >", value, "viewWeek");
            return (Criteria) this;
        }

        public Criteria andViewWeekGreaterThanOrEqualTo(Integer value) {
            addCriterion("view_week >=", value, "viewWeek");
            return (Criteria) this;
        }

        public Criteria andViewWeekLessThan(Integer value) {
            addCriterion("view_week <", value, "viewWeek");
            return (Criteria) this;
        }

        public Criteria andViewWeekLessThanOrEqualTo(Integer value) {
            addCriterion("view_week <=", value, "viewWeek");
            return (Criteria) this;
        }

        public Criteria andViewWeekIn(List<Integer> values) {
            addCriterion("view_week in", values, "viewWeek");
            return (Criteria) this;
        }

        public Criteria andViewWeekNotIn(List<Integer> values) {
            addCriterion("view_week not in", values, "viewWeek");
            return (Criteria) this;
        }

        public Criteria andViewWeekBetween(Integer value1, Integer value2) {
            addCriterion("view_week between", value1, value2, "viewWeek");
            return (Criteria) this;
        }

        public Criteria andViewWeekNotBetween(Integer value1, Integer value2) {
            addCriterion("view_week not between", value1, value2, "viewWeek");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table school_info
     *
     * @mbg.generated do_not_delete_during_merge Wed Jul 29 12:05:04 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table school_info
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}