package com.lexiangmiao.sample.mybatis.domain.cee;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table school_specialty
 */
public class SchoolSpecialtyKey extends BaseDomain {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_specialty.school_specialty_id
     *
     * @mbg.generated Thu Jul 30 10:42:19 CST 2020
     */
    private Long schoolSpecialtyId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_specialty.school_specialty_id
     *
     * @return the value of school_specialty.school_specialty_id
     *
     * @mbg.generated Thu Jul 30 10:42:19 CST 2020
     */
    public Long getSchoolSpecialtyId() {
        return schoolSpecialtyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_specialty.school_specialty_id
     *
     * @param schoolSpecialtyId the value for school_specialty.school_specialty_id
     *
     * @mbg.generated Thu Jul 30 10:42:19 CST 2020
     */
    public void setSchoolSpecialtyId(Long schoolSpecialtyId) {
        this.schoolSpecialtyId = schoolSpecialtyId;
    }
}