package com.lexiangmiao.sample.mybatis.domain.cee;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table school_info
 */
public class SchoolInfo extends SchoolInfoKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_info.address
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_info.admissions
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    private Integer admissions;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_info.answerurl
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    private String answerurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_info.belong
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    private String belong;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_info.central
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    private Integer central;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_info.city_id
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    private Integer cityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_info.city_name
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    private String cityName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_info.code_enroll
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    private Integer codeEnroll;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_info.colleges_level
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    private String collegesLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_info.county_id
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    private Integer countyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_info.county_name
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    private String countyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_info.department
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    private Integer department;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_info.doublehigh
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    private Integer doublehigh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_info.dual_class
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    private Integer dualClass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_info.dual_class_name
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    private String dualClassName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_info.f211
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    private Integer f211;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_info.f985
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    private Integer f985;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_info.id
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_info.is_recruitment
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    private Integer isRecruitment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_info.is_top
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    private Integer isTop;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_info.level
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_info.level_name
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    private String levelName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_info.name
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_info.nature
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    private Integer nature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_info.nature_name
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    private String natureName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_info.province_id
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    private Integer provinceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_info.province_name
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    private String provinceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_info.publish_id
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    private String publishId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_info.rank
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    private Integer rank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_info.rank_type
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    private Integer rankType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_info.school_id
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    private Integer schoolId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_info.school_type
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    private Integer schoolType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_info.single_province
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    private String singleProvince;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_info.type
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_info.type_name
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    private String typeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_info.view_month
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    private Integer viewMonth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_info.view_total
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    private String viewTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_info.view_total_number
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    private Integer viewTotalNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_info.view_week
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    private Integer viewWeek;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_info.address
     *
     * @return the value of school_info.address
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_info.address
     *
     * @param address the value for school_info.address
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_info.admissions
     *
     * @return the value of school_info.admissions
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public Integer getAdmissions() {
        return admissions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_info.admissions
     *
     * @param admissions the value for school_info.admissions
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public void setAdmissions(Integer admissions) {
        this.admissions = admissions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_info.answerurl
     *
     * @return the value of school_info.answerurl
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public String getAnswerurl() {
        return answerurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_info.answerurl
     *
     * @param answerurl the value for school_info.answerurl
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public void setAnswerurl(String answerurl) {
        this.answerurl = answerurl == null ? null : answerurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_info.belong
     *
     * @return the value of school_info.belong
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public String getBelong() {
        return belong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_info.belong
     *
     * @param belong the value for school_info.belong
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public void setBelong(String belong) {
        this.belong = belong == null ? null : belong.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_info.central
     *
     * @return the value of school_info.central
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public Integer getCentral() {
        return central;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_info.central
     *
     * @param central the value for school_info.central
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public void setCentral(Integer central) {
        this.central = central;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_info.city_id
     *
     * @return the value of school_info.city_id
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_info.city_id
     *
     * @param cityId the value for school_info.city_id
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_info.city_name
     *
     * @return the value of school_info.city_name
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_info.city_name
     *
     * @param cityName the value for school_info.city_name
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_info.code_enroll
     *
     * @return the value of school_info.code_enroll
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public Integer getCodeEnroll() {
        return codeEnroll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_info.code_enroll
     *
     * @param codeEnroll the value for school_info.code_enroll
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public void setCodeEnroll(Integer codeEnroll) {
        this.codeEnroll = codeEnroll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_info.colleges_level
     *
     * @return the value of school_info.colleges_level
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public String getCollegesLevel() {
        return collegesLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_info.colleges_level
     *
     * @param collegesLevel the value for school_info.colleges_level
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public void setCollegesLevel(String collegesLevel) {
        this.collegesLevel = collegesLevel == null ? null : collegesLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_info.county_id
     *
     * @return the value of school_info.county_id
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public Integer getCountyId() {
        return countyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_info.county_id
     *
     * @param countyId the value for school_info.county_id
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public void setCountyId(Integer countyId) {
        this.countyId = countyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_info.county_name
     *
     * @return the value of school_info.county_name
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public String getCountyName() {
        return countyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_info.county_name
     *
     * @param countyName the value for school_info.county_name
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public void setCountyName(String countyName) {
        this.countyName = countyName == null ? null : countyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_info.department
     *
     * @return the value of school_info.department
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public Integer getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_info.department
     *
     * @param department the value for school_info.department
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public void setDepartment(Integer department) {
        this.department = department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_info.doublehigh
     *
     * @return the value of school_info.doublehigh
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public Integer getDoublehigh() {
        return doublehigh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_info.doublehigh
     *
     * @param doublehigh the value for school_info.doublehigh
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public void setDoublehigh(Integer doublehigh) {
        this.doublehigh = doublehigh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_info.dual_class
     *
     * @return the value of school_info.dual_class
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public Integer getDualClass() {
        return dualClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_info.dual_class
     *
     * @param dualClass the value for school_info.dual_class
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public void setDualClass(Integer dualClass) {
        this.dualClass = dualClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_info.dual_class_name
     *
     * @return the value of school_info.dual_class_name
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public String getDualClassName() {
        return dualClassName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_info.dual_class_name
     *
     * @param dualClassName the value for school_info.dual_class_name
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public void setDualClassName(String dualClassName) {
        this.dualClassName = dualClassName == null ? null : dualClassName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_info.f211
     *
     * @return the value of school_info.f211
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public Integer getF211() {
        return f211;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_info.f211
     *
     * @param f211 the value for school_info.f211
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public void setF211(Integer f211) {
        this.f211 = f211;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_info.f985
     *
     * @return the value of school_info.f985
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public Integer getF985() {
        return f985;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_info.f985
     *
     * @param f985 the value for school_info.f985
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public void setF985(Integer f985) {
        this.f985 = f985;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_info.id
     *
     * @return the value of school_info.id
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_info.id
     *
     * @param id the value for school_info.id
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_info.is_recruitment
     *
     * @return the value of school_info.is_recruitment
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public Integer getIsRecruitment() {
        return isRecruitment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_info.is_recruitment
     *
     * @param isRecruitment the value for school_info.is_recruitment
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public void setIsRecruitment(Integer isRecruitment) {
        this.isRecruitment = isRecruitment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_info.is_top
     *
     * @return the value of school_info.is_top
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public Integer getIsTop() {
        return isTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_info.is_top
     *
     * @param isTop the value for school_info.is_top
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public void setIsTop(Integer isTop) {
        this.isTop = isTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_info.level
     *
     * @return the value of school_info.level
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_info.level
     *
     * @param level the value for school_info.level
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_info.level_name
     *
     * @return the value of school_info.level_name
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public String getLevelName() {
        return levelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_info.level_name
     *
     * @param levelName the value for school_info.level_name
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public void setLevelName(String levelName) {
        this.levelName = levelName == null ? null : levelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_info.name
     *
     * @return the value of school_info.name
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_info.name
     *
     * @param name the value for school_info.name
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_info.nature
     *
     * @return the value of school_info.nature
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public Integer getNature() {
        return nature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_info.nature
     *
     * @param nature the value for school_info.nature
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public void setNature(Integer nature) {
        this.nature = nature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_info.nature_name
     *
     * @return the value of school_info.nature_name
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public String getNatureName() {
        return natureName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_info.nature_name
     *
     * @param natureName the value for school_info.nature_name
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public void setNatureName(String natureName) {
        this.natureName = natureName == null ? null : natureName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_info.province_id
     *
     * @return the value of school_info.province_id
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public Integer getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_info.province_id
     *
     * @param provinceId the value for school_info.province_id
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public void setProvinceId(Integer provinceId) {
        this.provinceId = provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_info.province_name
     *
     * @return the value of school_info.province_name
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_info.province_name
     *
     * @param provinceName the value for school_info.province_name
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName == null ? null : provinceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_info.publish_id
     *
     * @return the value of school_info.publish_id
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public String getPublishId() {
        return publishId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_info.publish_id
     *
     * @param publishId the value for school_info.publish_id
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public void setPublishId(String publishId) {
        this.publishId = publishId == null ? null : publishId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_info.rank
     *
     * @return the value of school_info.rank
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public Integer getRank() {
        return rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_info.rank
     *
     * @param rank the value for school_info.rank
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public void setRank(Integer rank) {
        this.rank = rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_info.rank_type
     *
     * @return the value of school_info.rank_type
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public Integer getRankType() {
        return rankType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_info.rank_type
     *
     * @param rankType the value for school_info.rank_type
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public void setRankType(Integer rankType) {
        this.rankType = rankType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_info.school_id
     *
     * @return the value of school_info.school_id
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public Integer getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_info.school_id
     *
     * @param schoolId the value for school_info.school_id
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public void setSchoolId(Integer schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_info.school_type
     *
     * @return the value of school_info.school_type
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public Integer getSchoolType() {
        return schoolType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_info.school_type
     *
     * @param schoolType the value for school_info.school_type
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public void setSchoolType(Integer schoolType) {
        this.schoolType = schoolType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_info.single_province
     *
     * @return the value of school_info.single_province
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public String getSingleProvince() {
        return singleProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_info.single_province
     *
     * @param singleProvince the value for school_info.single_province
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public void setSingleProvince(String singleProvince) {
        this.singleProvince = singleProvince == null ? null : singleProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_info.type
     *
     * @return the value of school_info.type
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_info.type
     *
     * @param type the value for school_info.type
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_info.type_name
     *
     * @return the value of school_info.type_name
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_info.type_name
     *
     * @param typeName the value for school_info.type_name
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_info.view_month
     *
     * @return the value of school_info.view_month
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public Integer getViewMonth() {
        return viewMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_info.view_month
     *
     * @param viewMonth the value for school_info.view_month
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public void setViewMonth(Integer viewMonth) {
        this.viewMonth = viewMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_info.view_total
     *
     * @return the value of school_info.view_total
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public String getViewTotal() {
        return viewTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_info.view_total
     *
     * @param viewTotal the value for school_info.view_total
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public void setViewTotal(String viewTotal) {
        this.viewTotal = viewTotal == null ? null : viewTotal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_info.view_total_number
     *
     * @return the value of school_info.view_total_number
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public Integer getViewTotalNumber() {
        return viewTotalNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_info.view_total_number
     *
     * @param viewTotalNumber the value for school_info.view_total_number
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public void setViewTotalNumber(Integer viewTotalNumber) {
        this.viewTotalNumber = viewTotalNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_info.view_week
     *
     * @return the value of school_info.view_week
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public Integer getViewWeek() {
        return viewWeek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_info.view_week
     *
     * @param viewWeek the value for school_info.view_week
     *
     * @mbg.generated Wed Jul 29 12:05:04 CST 2020
     */
    public void setViewWeek(Integer viewWeek) {
        this.viewWeek = viewWeek;
    }
}