package com.lexiangmiao.sample.mybatis.domain.cee;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table school_specialty
 */
public class SchoolSpecialty extends SchoolSpecialtyKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_specialty.school_id
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    private String schoolId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_specialty.special_id
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    private String specialId;

    /**
     * Database Column Remarks:
     *   文理科
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_specialty.type
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    private String type;

    /**
     * Database Column Remarks:
     *   最高分
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_specialty.max
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    private Double max;

    /**
     * Database Column Remarks:
     *   最低分
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_specialty.min
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    private Double min;

    /**
     * Database Column Remarks:
     *   平均分
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_specialty.average
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    private Double average;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_specialty.min_section
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    private Integer minSection;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_specialty.province
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_specialty.batch
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    private String batch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_specialty.id
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_specialty.spid
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    private Integer spid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_specialty.zslx
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    private String zslx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_specialty.info
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    private String info;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_specialty.level1_name
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    private String level1Name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_specialty.level2_name
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    private String level2Name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_specialty.level3_name
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    private String level3Name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_specialty.level1
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    private String level1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_specialty.level2
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    private String level2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_specialty.spname
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    private String spname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_specialty.level3
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    private String level3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_specialty.local_batch_name
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    private String localBatchName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_specialty.zslx_name
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    private String zslxName;

    /**
     * Database Column Remarks:
     *   年份
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_specialty.year
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    private Integer year;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_specialty.school_id
     *
     * @return the value of school_specialty.school_id
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    public String getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_specialty.school_id
     *
     * @param schoolId the value for school_specialty.school_id
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    public void setSchoolId(String schoolId) {
        this.schoolId = schoolId == null ? null : schoolId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_specialty.special_id
     *
     * @return the value of school_specialty.special_id
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    public String getSpecialId() {
        return specialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_specialty.special_id
     *
     * @param specialId the value for school_specialty.special_id
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    public void setSpecialId(String specialId) {
        this.specialId = specialId == null ? null : specialId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_specialty.type
     *
     * @return the value of school_specialty.type
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_specialty.type
     *
     * @param type the value for school_specialty.type
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_specialty.max
     *
     * @return the value of school_specialty.max
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    public Double getMax() {
        return max;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_specialty.max
     *
     * @param max the value for school_specialty.max
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    public void setMax(Double max) {
        this.max = max;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_specialty.min
     *
     * @return the value of school_specialty.min
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    public Double getMin() {
        return min;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_specialty.min
     *
     * @param min the value for school_specialty.min
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    public void setMin(Double min) {
        this.min = min;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_specialty.average
     *
     * @return the value of school_specialty.average
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    public Double getAverage() {
        return average;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_specialty.average
     *
     * @param average the value for school_specialty.average
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    public void setAverage(Double average) {
        this.average = average;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_specialty.min_section
     *
     * @return the value of school_specialty.min_section
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    public Integer getMinSection() {
        return minSection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_specialty.min_section
     *
     * @param minSection the value for school_specialty.min_section
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    public void setMinSection(Integer minSection) {
        this.minSection = minSection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_specialty.province
     *
     * @return the value of school_specialty.province
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_specialty.province
     *
     * @param province the value for school_specialty.province
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_specialty.batch
     *
     * @return the value of school_specialty.batch
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    public String getBatch() {
        return batch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_specialty.batch
     *
     * @param batch the value for school_specialty.batch
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    public void setBatch(String batch) {
        this.batch = batch == null ? null : batch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_specialty.id
     *
     * @return the value of school_specialty.id
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_specialty.id
     *
     * @param id the value for school_specialty.id
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_specialty.spid
     *
     * @return the value of school_specialty.spid
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    public Integer getSpid() {
        return spid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_specialty.spid
     *
     * @param spid the value for school_specialty.spid
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    public void setSpid(Integer spid) {
        this.spid = spid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_specialty.zslx
     *
     * @return the value of school_specialty.zslx
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    public String getZslx() {
        return zslx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_specialty.zslx
     *
     * @param zslx the value for school_specialty.zslx
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    public void setZslx(String zslx) {
        this.zslx = zslx == null ? null : zslx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_specialty.info
     *
     * @return the value of school_specialty.info
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_specialty.info
     *
     * @param info the value for school_specialty.info
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    public void setInfo(String info) {
        this.info = info == null ? null : info.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_specialty.level1_name
     *
     * @return the value of school_specialty.level1_name
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    public String getLevel1Name() {
        return level1Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_specialty.level1_name
     *
     * @param level1Name the value for school_specialty.level1_name
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    public void setLevel1Name(String level1Name) {
        this.level1Name = level1Name == null ? null : level1Name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_specialty.level2_name
     *
     * @return the value of school_specialty.level2_name
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    public String getLevel2Name() {
        return level2Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_specialty.level2_name
     *
     * @param level2Name the value for school_specialty.level2_name
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    public void setLevel2Name(String level2Name) {
        this.level2Name = level2Name == null ? null : level2Name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_specialty.level3_name
     *
     * @return the value of school_specialty.level3_name
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    public String getLevel3Name() {
        return level3Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_specialty.level3_name
     *
     * @param level3Name the value for school_specialty.level3_name
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    public void setLevel3Name(String level3Name) {
        this.level3Name = level3Name == null ? null : level3Name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_specialty.level1
     *
     * @return the value of school_specialty.level1
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    public String getLevel1() {
        return level1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_specialty.level1
     *
     * @param level1 the value for school_specialty.level1
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    public void setLevel1(String level1) {
        this.level1 = level1 == null ? null : level1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_specialty.level2
     *
     * @return the value of school_specialty.level2
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    public String getLevel2() {
        return level2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_specialty.level2
     *
     * @param level2 the value for school_specialty.level2
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    public void setLevel2(String level2) {
        this.level2 = level2 == null ? null : level2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_specialty.spname
     *
     * @return the value of school_specialty.spname
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    public String getSpname() {
        return spname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_specialty.spname
     *
     * @param spname the value for school_specialty.spname
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    public void setSpname(String spname) {
        this.spname = spname == null ? null : spname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_specialty.level3
     *
     * @return the value of school_specialty.level3
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    public String getLevel3() {
        return level3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_specialty.level3
     *
     * @param level3 the value for school_specialty.level3
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    public void setLevel3(String level3) {
        this.level3 = level3 == null ? null : level3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_specialty.local_batch_name
     *
     * @return the value of school_specialty.local_batch_name
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    public String getLocalBatchName() {
        return localBatchName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_specialty.local_batch_name
     *
     * @param localBatchName the value for school_specialty.local_batch_name
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    public void setLocalBatchName(String localBatchName) {
        this.localBatchName = localBatchName == null ? null : localBatchName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_specialty.zslx_name
     *
     * @return the value of school_specialty.zslx_name
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    public String getZslxName() {
        return zslxName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_specialty.zslx_name
     *
     * @param zslxName the value for school_specialty.zslx_name
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    public void setZslxName(String zslxName) {
        this.zslxName = zslxName == null ? null : zslxName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_specialty.year
     *
     * @return the value of school_specialty.year
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_specialty.year
     *
     * @param year the value for school_specialty.year
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    public void setYear(Integer year) {
        this.year = year;
    }
}