server:
  port: 9527


spring:
  application:
    name: cloud-geteway
#### 静态路由
#  cloud:
#    gateway:
#      routes:
#        - id: payment_route1
#          uri: http://localhost:8001
#          predicates: #断言
#            - Path=/payment/get/**
#
#        - id: payment_route2
#          uri: http://localhost:8001
#          predicates:
#            - Path=/payment/lb/**
### 动态路由
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用服务器名进行路由
      routes:
        - id: payment_route1
          uri: lb://cloud-payment-service
          predicates: #断言
            - Path=/payment/get/**

        - id: payment_route2
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**

eureka:
  instance:
    hostname: cloud-geteway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
#      defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
