package com.lexiangmiao.sample.mybatis.domain.cee;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table school_plan
 */
public class SchoolPlanKey extends BaseDomain {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_plan.school_plan_id
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    private Long schoolPlanId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_plan.school_plan_id
     *
     * @return the value of school_plan.school_plan_id
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    public Long getSchoolPlanId() {
        return schoolPlanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_plan.school_plan_id
     *
     * @param schoolPlanId the value for school_plan.school_plan_id
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    public void setSchoolPlanId(Long schoolPlanId) {
        this.schoolPlanId = schoolPlanId;
    }
}