package com.lexiangmiao.sample.mybatis.domain.cee;

import java.util.ArrayList;
import java.util.List;

public class SchoolSpecialtyExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table school_specialty
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table school_specialty
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table school_specialty
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_specialty
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    public SchoolSpecialtyExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_specialty
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_specialty
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_specialty
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_specialty
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_specialty
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_specialty
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_specialty
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_specialty
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_specialty
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_specialty
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table school_specialty
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSchoolSpecialtyIdIsNull() {
            addCriterion("school_specialty_id is null");
            return (Criteria) this;
        }

        public Criteria andSchoolSpecialtyIdIsNotNull() {
            addCriterion("school_specialty_id is not null");
            return (Criteria) this;
        }

        public Criteria andSchoolSpecialtyIdEqualTo(Long value) {
            addCriterion("school_specialty_id =", value, "schoolSpecialtyId");
            return (Criteria) this;
        }

        public Criteria andSchoolSpecialtyIdNotEqualTo(Long value) {
            addCriterion("school_specialty_id <>", value, "schoolSpecialtyId");
            return (Criteria) this;
        }

        public Criteria andSchoolSpecialtyIdGreaterThan(Long value) {
            addCriterion("school_specialty_id >", value, "schoolSpecialtyId");
            return (Criteria) this;
        }

        public Criteria andSchoolSpecialtyIdGreaterThanOrEqualTo(Long value) {
            addCriterion("school_specialty_id >=", value, "schoolSpecialtyId");
            return (Criteria) this;
        }

        public Criteria andSchoolSpecialtyIdLessThan(Long value) {
            addCriterion("school_specialty_id <", value, "schoolSpecialtyId");
            return (Criteria) this;
        }

        public Criteria andSchoolSpecialtyIdLessThanOrEqualTo(Long value) {
            addCriterion("school_specialty_id <=", value, "schoolSpecialtyId");
            return (Criteria) this;
        }

        public Criteria andSchoolSpecialtyIdIn(List<Long> values) {
            addCriterion("school_specialty_id in", values, "schoolSpecialtyId");
            return (Criteria) this;
        }

        public Criteria andSchoolSpecialtyIdNotIn(List<Long> values) {
            addCriterion("school_specialty_id not in", values, "schoolSpecialtyId");
            return (Criteria) this;
        }

        public Criteria andSchoolSpecialtyIdBetween(Long value1, Long value2) {
            addCriterion("school_specialty_id between", value1, value2, "schoolSpecialtyId");
            return (Criteria) this;
        }

        public Criteria andSchoolSpecialtyIdNotBetween(Long value1, Long value2) {
            addCriterion("school_specialty_id not between", value1, value2, "schoolSpecialtyId");
            return (Criteria) this;
        }

        public Criteria andSchoolIdIsNull() {
            addCriterion("school_id is null");
            return (Criteria) this;
        }

        public Criteria andSchoolIdIsNotNull() {
            addCriterion("school_id is not null");
            return (Criteria) this;
        }

        public Criteria andSchoolIdEqualTo(String value) {
            addCriterion("school_id =", value, "schoolId");
            return (Criteria) this;
        }

        public Criteria andSchoolIdNotEqualTo(String value) {
            addCriterion("school_id <>", value, "schoolId");
            return (Criteria) this;
        }

        public Criteria andSchoolIdGreaterThan(String value) {
            addCriterion("school_id >", value, "schoolId");
            return (Criteria) this;
        }

        public Criteria andSchoolIdGreaterThanOrEqualTo(String value) {
            addCriterion("school_id >=", value, "schoolId");
            return (Criteria) this;
        }

        public Criteria andSchoolIdLessThan(String value) {
            addCriterion("school_id <", value, "schoolId");
            return (Criteria) this;
        }

        public Criteria andSchoolIdLessThanOrEqualTo(String value) {
            addCriterion("school_id <=", value, "schoolId");
            return (Criteria) this;
        }

        public Criteria andSchoolIdLike(String value) {
            addCriterion("school_id like", value, "schoolId");
            return (Criteria) this;
        }

        public Criteria andSchoolIdNotLike(String value) {
            addCriterion("school_id not like", value, "schoolId");
            return (Criteria) this;
        }

        public Criteria andSchoolIdIn(List<String> values) {
            addCriterion("school_id in", values, "schoolId");
            return (Criteria) this;
        }

        public Criteria andSchoolIdNotIn(List<String> values) {
            addCriterion("school_id not in", values, "schoolId");
            return (Criteria) this;
        }

        public Criteria andSchoolIdBetween(String value1, String value2) {
            addCriterion("school_id between", value1, value2, "schoolId");
            return (Criteria) this;
        }

        public Criteria andSchoolIdNotBetween(String value1, String value2) {
            addCriterion("school_id not between", value1, value2, "schoolId");
            return (Criteria) this;
        }

        public Criteria andSpecialIdIsNull() {
            addCriterion("special_id is null");
            return (Criteria) this;
        }

        public Criteria andSpecialIdIsNotNull() {
            addCriterion("special_id is not null");
            return (Criteria) this;
        }

        public Criteria andSpecialIdEqualTo(String value) {
            addCriterion("special_id =", value, "specialId");
            return (Criteria) this;
        }

        public Criteria andSpecialIdNotEqualTo(String value) {
            addCriterion("special_id <>", value, "specialId");
            return (Criteria) this;
        }

        public Criteria andSpecialIdGreaterThan(String value) {
            addCriterion("special_id >", value, "specialId");
            return (Criteria) this;
        }

        public Criteria andSpecialIdGreaterThanOrEqualTo(String value) {
            addCriterion("special_id >=", value, "specialId");
            return (Criteria) this;
        }

        public Criteria andSpecialIdLessThan(String value) {
            addCriterion("special_id <", value, "specialId");
            return (Criteria) this;
        }

        public Criteria andSpecialIdLessThanOrEqualTo(String value) {
            addCriterion("special_id <=", value, "specialId");
            return (Criteria) this;
        }

        public Criteria andSpecialIdLike(String value) {
            addCriterion("special_id like", value, "specialId");
            return (Criteria) this;
        }

        public Criteria andSpecialIdNotLike(String value) {
            addCriterion("special_id not like", value, "specialId");
            return (Criteria) this;
        }

        public Criteria andSpecialIdIn(List<String> values) {
            addCriterion("special_id in", values, "specialId");
            return (Criteria) this;
        }

        public Criteria andSpecialIdNotIn(List<String> values) {
            addCriterion("special_id not in", values, "specialId");
            return (Criteria) this;
        }

        public Criteria andSpecialIdBetween(String value1, String value2) {
            addCriterion("special_id between", value1, value2, "specialId");
            return (Criteria) this;
        }

        public Criteria andSpecialIdNotBetween(String value1, String value2) {
            addCriterion("special_id not between", value1, value2, "specialId");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andMaxIsNull() {
            addCriterion("max is null");
            return (Criteria) this;
        }

        public Criteria andMaxIsNotNull() {
            addCriterion("max is not null");
            return (Criteria) this;
        }

        public Criteria andMaxEqualTo(Double value) {
            addCriterion("max =", value, "max");
            return (Criteria) this;
        }

        public Criteria andMaxNotEqualTo(Double value) {
            addCriterion("max <>", value, "max");
            return (Criteria) this;
        }

        public Criteria andMaxGreaterThan(Double value) {
            addCriterion("max >", value, "max");
            return (Criteria) this;
        }

        public Criteria andMaxGreaterThanOrEqualTo(Double value) {
            addCriterion("max >=", value, "max");
            return (Criteria) this;
        }

        public Criteria andMaxLessThan(Double value) {
            addCriterion("max <", value, "max");
            return (Criteria) this;
        }

        public Criteria andMaxLessThanOrEqualTo(Double value) {
            addCriterion("max <=", value, "max");
            return (Criteria) this;
        }

        public Criteria andMaxIn(List<Double> values) {
            addCriterion("max in", values, "max");
            return (Criteria) this;
        }

        public Criteria andMaxNotIn(List<Double> values) {
            addCriterion("max not in", values, "max");
            return (Criteria) this;
        }

        public Criteria andMaxBetween(Double value1, Double value2) {
            addCriterion("max between", value1, value2, "max");
            return (Criteria) this;
        }

        public Criteria andMaxNotBetween(Double value1, Double value2) {
            addCriterion("max not between", value1, value2, "max");
            return (Criteria) this;
        }

        public Criteria andMinIsNull() {
            addCriterion("min is null");
            return (Criteria) this;
        }

        public Criteria andMinIsNotNull() {
            addCriterion("min is not null");
            return (Criteria) this;
        }

        public Criteria andMinEqualTo(Double value) {
            addCriterion("min =", value, "min");
            return (Criteria) this;
        }

        public Criteria andMinNotEqualTo(Double value) {
            addCriterion("min <>", value, "min");
            return (Criteria) this;
        }

        public Criteria andMinGreaterThan(Double value) {
            addCriterion("min >", value, "min");
            return (Criteria) this;
        }

        public Criteria andMinGreaterThanOrEqualTo(Double value) {
            addCriterion("min >=", value, "min");
            return (Criteria) this;
        }

        public Criteria andMinLessThan(Double value) {
            addCriterion("min <", value, "min");
            return (Criteria) this;
        }

        public Criteria andMinLessThanOrEqualTo(Double value) {
            addCriterion("min <=", value, "min");
            return (Criteria) this;
        }

        public Criteria andMinIn(List<Double> values) {
            addCriterion("min in", values, "min");
            return (Criteria) this;
        }

        public Criteria andMinNotIn(List<Double> values) {
            addCriterion("min not in", values, "min");
            return (Criteria) this;
        }

        public Criteria andMinBetween(Double value1, Double value2) {
            addCriterion("min between", value1, value2, "min");
            return (Criteria) this;
        }

        public Criteria andMinNotBetween(Double value1, Double value2) {
            addCriterion("min not between", value1, value2, "min");
            return (Criteria) this;
        }

        public Criteria andAverageIsNull() {
            addCriterion("average is null");
            return (Criteria) this;
        }

        public Criteria andAverageIsNotNull() {
            addCriterion("average is not null");
            return (Criteria) this;
        }

        public Criteria andAverageEqualTo(Double value) {
            addCriterion("average =", value, "average");
            return (Criteria) this;
        }

        public Criteria andAverageNotEqualTo(Double value) {
            addCriterion("average <>", value, "average");
            return (Criteria) this;
        }

        public Criteria andAverageGreaterThan(Double value) {
            addCriterion("average >", value, "average");
            return (Criteria) this;
        }

        public Criteria andAverageGreaterThanOrEqualTo(Double value) {
            addCriterion("average >=", value, "average");
            return (Criteria) this;
        }

        public Criteria andAverageLessThan(Double value) {
            addCriterion("average <", value, "average");
            return (Criteria) this;
        }

        public Criteria andAverageLessThanOrEqualTo(Double value) {
            addCriterion("average <=", value, "average");
            return (Criteria) this;
        }

        public Criteria andAverageIn(List<Double> values) {
            addCriterion("average in", values, "average");
            return (Criteria) this;
        }

        public Criteria andAverageNotIn(List<Double> values) {
            addCriterion("average not in", values, "average");
            return (Criteria) this;
        }

        public Criteria andAverageBetween(Double value1, Double value2) {
            addCriterion("average between", value1, value2, "average");
            return (Criteria) this;
        }

        public Criteria andAverageNotBetween(Double value1, Double value2) {
            addCriterion("average not between", value1, value2, "average");
            return (Criteria) this;
        }

        public Criteria andMinSectionIsNull() {
            addCriterion("min_section is null");
            return (Criteria) this;
        }

        public Criteria andMinSectionIsNotNull() {
            addCriterion("min_section is not null");
            return (Criteria) this;
        }

        public Criteria andMinSectionEqualTo(Integer value) {
            addCriterion("min_section =", value, "minSection");
            return (Criteria) this;
        }

        public Criteria andMinSectionNotEqualTo(Integer value) {
            addCriterion("min_section <>", value, "minSection");
            return (Criteria) this;
        }

        public Criteria andMinSectionGreaterThan(Integer value) {
            addCriterion("min_section >", value, "minSection");
            return (Criteria) this;
        }

        public Criteria andMinSectionGreaterThanOrEqualTo(Integer value) {
            addCriterion("min_section >=", value, "minSection");
            return (Criteria) this;
        }

        public Criteria andMinSectionLessThan(Integer value) {
            addCriterion("min_section <", value, "minSection");
            return (Criteria) this;
        }

        public Criteria andMinSectionLessThanOrEqualTo(Integer value) {
            addCriterion("min_section <=", value, "minSection");
            return (Criteria) this;
        }

        public Criteria andMinSectionIn(List<Integer> values) {
            addCriterion("min_section in", values, "minSection");
            return (Criteria) this;
        }

        public Criteria andMinSectionNotIn(List<Integer> values) {
            addCriterion("min_section not in", values, "minSection");
            return (Criteria) this;
        }

        public Criteria andMinSectionBetween(Integer value1, Integer value2) {
            addCriterion("min_section between", value1, value2, "minSection");
            return (Criteria) this;
        }

        public Criteria andMinSectionNotBetween(Integer value1, Integer value2) {
            addCriterion("min_section not between", value1, value2, "minSection");
            return (Criteria) this;
        }

        public Criteria andProvinceIsNull() {
            addCriterion("province is null");
            return (Criteria) this;
        }

        public Criteria andProvinceIsNotNull() {
            addCriterion("province is not null");
            return (Criteria) this;
        }

        public Criteria andProvinceEqualTo(String value) {
            addCriterion("province =", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotEqualTo(String value) {
            addCriterion("province <>", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceGreaterThan(String value) {
            addCriterion("province >", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceGreaterThanOrEqualTo(String value) {
            addCriterion("province >=", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLessThan(String value) {
            addCriterion("province <", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLessThanOrEqualTo(String value) {
            addCriterion("province <=", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLike(String value) {
            addCriterion("province like", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotLike(String value) {
            addCriterion("province not like", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceIn(List<String> values) {
            addCriterion("province in", values, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotIn(List<String> values) {
            addCriterion("province not in", values, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceBetween(String value1, String value2) {
            addCriterion("province between", value1, value2, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotBetween(String value1, String value2) {
            addCriterion("province not between", value1, value2, "province");
            return (Criteria) this;
        }

        public Criteria andBatchIsNull() {
            addCriterion("batch is null");
            return (Criteria) this;
        }

        public Criteria andBatchIsNotNull() {
            addCriterion("batch is not null");
            return (Criteria) this;
        }

        public Criteria andBatchEqualTo(String value) {
            addCriterion("batch =", value, "batch");
            return (Criteria) this;
        }

        public Criteria andBatchNotEqualTo(String value) {
            addCriterion("batch <>", value, "batch");
            return (Criteria) this;
        }

        public Criteria andBatchGreaterThan(String value) {
            addCriterion("batch >", value, "batch");
            return (Criteria) this;
        }

        public Criteria andBatchGreaterThanOrEqualTo(String value) {
            addCriterion("batch >=", value, "batch");
            return (Criteria) this;
        }

        public Criteria andBatchLessThan(String value) {
            addCriterion("batch <", value, "batch");
            return (Criteria) this;
        }

        public Criteria andBatchLessThanOrEqualTo(String value) {
            addCriterion("batch <=", value, "batch");
            return (Criteria) this;
        }

        public Criteria andBatchLike(String value) {
            addCriterion("batch like", value, "batch");
            return (Criteria) this;
        }

        public Criteria andBatchNotLike(String value) {
            addCriterion("batch not like", value, "batch");
            return (Criteria) this;
        }

        public Criteria andBatchIn(List<String> values) {
            addCriterion("batch in", values, "batch");
            return (Criteria) this;
        }

        public Criteria andBatchNotIn(List<String> values) {
            addCriterion("batch not in", values, "batch");
            return (Criteria) this;
        }

        public Criteria andBatchBetween(String value1, String value2) {
            addCriterion("batch between", value1, value2, "batch");
            return (Criteria) this;
        }

        public Criteria andBatchNotBetween(String value1, String value2) {
            addCriterion("batch not between", value1, value2, "batch");
            return (Criteria) this;
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSpidIsNull() {
            addCriterion("spid is null");
            return (Criteria) this;
        }

        public Criteria andSpidIsNotNull() {
            addCriterion("spid is not null");
            return (Criteria) this;
        }

        public Criteria andSpidEqualTo(Integer value) {
            addCriterion("spid =", value, "spid");
            return (Criteria) this;
        }

        public Criteria andSpidNotEqualTo(Integer value) {
            addCriterion("spid <>", value, "spid");
            return (Criteria) this;
        }

        public Criteria andSpidGreaterThan(Integer value) {
            addCriterion("spid >", value, "spid");
            return (Criteria) this;
        }

        public Criteria andSpidGreaterThanOrEqualTo(Integer value) {
            addCriterion("spid >=", value, "spid");
            return (Criteria) this;
        }

        public Criteria andSpidLessThan(Integer value) {
            addCriterion("spid <", value, "spid");
            return (Criteria) this;
        }

        public Criteria andSpidLessThanOrEqualTo(Integer value) {
            addCriterion("spid <=", value, "spid");
            return (Criteria) this;
        }

        public Criteria andSpidIn(List<Integer> values) {
            addCriterion("spid in", values, "spid");
            return (Criteria) this;
        }

        public Criteria andSpidNotIn(List<Integer> values) {
            addCriterion("spid not in", values, "spid");
            return (Criteria) this;
        }

        public Criteria andSpidBetween(Integer value1, Integer value2) {
            addCriterion("spid between", value1, value2, "spid");
            return (Criteria) this;
        }

        public Criteria andSpidNotBetween(Integer value1, Integer value2) {
            addCriterion("spid not between", value1, value2, "spid");
            return (Criteria) this;
        }

        public Criteria andZslxIsNull() {
            addCriterion("zslx is null");
            return (Criteria) this;
        }

        public Criteria andZslxIsNotNull() {
            addCriterion("zslx is not null");
            return (Criteria) this;
        }

        public Criteria andZslxEqualTo(String value) {
            addCriterion("zslx =", value, "zslx");
            return (Criteria) this;
        }

        public Criteria andZslxNotEqualTo(String value) {
            addCriterion("zslx <>", value, "zslx");
            return (Criteria) this;
        }

        public Criteria andZslxGreaterThan(String value) {
            addCriterion("zslx >", value, "zslx");
            return (Criteria) this;
        }

        public Criteria andZslxGreaterThanOrEqualTo(String value) {
            addCriterion("zslx >=", value, "zslx");
            return (Criteria) this;
        }

        public Criteria andZslxLessThan(String value) {
            addCriterion("zslx <", value, "zslx");
            return (Criteria) this;
        }

        public Criteria andZslxLessThanOrEqualTo(String value) {
            addCriterion("zslx <=", value, "zslx");
            return (Criteria) this;
        }

        public Criteria andZslxLike(String value) {
            addCriterion("zslx like", value, "zslx");
            return (Criteria) this;
        }

        public Criteria andZslxNotLike(String value) {
            addCriterion("zslx not like", value, "zslx");
            return (Criteria) this;
        }

        public Criteria andZslxIn(List<String> values) {
            addCriterion("zslx in", values, "zslx");
            return (Criteria) this;
        }

        public Criteria andZslxNotIn(List<String> values) {
            addCriterion("zslx not in", values, "zslx");
            return (Criteria) this;
        }

        public Criteria andZslxBetween(String value1, String value2) {
            addCriterion("zslx between", value1, value2, "zslx");
            return (Criteria) this;
        }

        public Criteria andZslxNotBetween(String value1, String value2) {
            addCriterion("zslx not between", value1, value2, "zslx");
            return (Criteria) this;
        }

        public Criteria andInfoIsNull() {
            addCriterion("info is null");
            return (Criteria) this;
        }

        public Criteria andInfoIsNotNull() {
            addCriterion("info is not null");
            return (Criteria) this;
        }

        public Criteria andInfoEqualTo(String value) {
            addCriterion("info =", value, "info");
            return (Criteria) this;
        }

        public Criteria andInfoNotEqualTo(String value) {
            addCriterion("info <>", value, "info");
            return (Criteria) this;
        }

        public Criteria andInfoGreaterThan(String value) {
            addCriterion("info >", value, "info");
            return (Criteria) this;
        }

        public Criteria andInfoGreaterThanOrEqualTo(String value) {
            addCriterion("info >=", value, "info");
            return (Criteria) this;
        }

        public Criteria andInfoLessThan(String value) {
            addCriterion("info <", value, "info");
            return (Criteria) this;
        }

        public Criteria andInfoLessThanOrEqualTo(String value) {
            addCriterion("info <=", value, "info");
            return (Criteria) this;
        }

        public Criteria andInfoLike(String value) {
            addCriterion("info like", value, "info");
            return (Criteria) this;
        }

        public Criteria andInfoNotLike(String value) {
            addCriterion("info not like", value, "info");
            return (Criteria) this;
        }

        public Criteria andInfoIn(List<String> values) {
            addCriterion("info in", values, "info");
            return (Criteria) this;
        }

        public Criteria andInfoNotIn(List<String> values) {
            addCriterion("info not in", values, "info");
            return (Criteria) this;
        }

        public Criteria andInfoBetween(String value1, String value2) {
            addCriterion("info between", value1, value2, "info");
            return (Criteria) this;
        }

        public Criteria andInfoNotBetween(String value1, String value2) {
            addCriterion("info not between", value1, value2, "info");
            return (Criteria) this;
        }

        public Criteria andLevel1NameIsNull() {
            addCriterion("level1_name is null");
            return (Criteria) this;
        }

        public Criteria andLevel1NameIsNotNull() {
            addCriterion("level1_name is not null");
            return (Criteria) this;
        }

        public Criteria andLevel1NameEqualTo(String value) {
            addCriterion("level1_name =", value, "level1Name");
            return (Criteria) this;
        }

        public Criteria andLevel1NameNotEqualTo(String value) {
            addCriterion("level1_name <>", value, "level1Name");
            return (Criteria) this;
        }

        public Criteria andLevel1NameGreaterThan(String value) {
            addCriterion("level1_name >", value, "level1Name");
            return (Criteria) this;
        }

        public Criteria andLevel1NameGreaterThanOrEqualTo(String value) {
            addCriterion("level1_name >=", value, "level1Name");
            return (Criteria) this;
        }

        public Criteria andLevel1NameLessThan(String value) {
            addCriterion("level1_name <", value, "level1Name");
            return (Criteria) this;
        }

        public Criteria andLevel1NameLessThanOrEqualTo(String value) {
            addCriterion("level1_name <=", value, "level1Name");
            return (Criteria) this;
        }

        public Criteria andLevel1NameLike(String value) {
            addCriterion("level1_name like", value, "level1Name");
            return (Criteria) this;
        }

        public Criteria andLevel1NameNotLike(String value) {
            addCriterion("level1_name not like", value, "level1Name");
            return (Criteria) this;
        }

        public Criteria andLevel1NameIn(List<String> values) {
            addCriterion("level1_name in", values, "level1Name");
            return (Criteria) this;
        }

        public Criteria andLevel1NameNotIn(List<String> values) {
            addCriterion("level1_name not in", values, "level1Name");
            return (Criteria) this;
        }

        public Criteria andLevel1NameBetween(String value1, String value2) {
            addCriterion("level1_name between", value1, value2, "level1Name");
            return (Criteria) this;
        }

        public Criteria andLevel1NameNotBetween(String value1, String value2) {
            addCriterion("level1_name not between", value1, value2, "level1Name");
            return (Criteria) this;
        }

        public Criteria andLevel2NameIsNull() {
            addCriterion("level2_name is null");
            return (Criteria) this;
        }

        public Criteria andLevel2NameIsNotNull() {
            addCriterion("level2_name is not null");
            return (Criteria) this;
        }

        public Criteria andLevel2NameEqualTo(String value) {
            addCriterion("level2_name =", value, "level2Name");
            return (Criteria) this;
        }

        public Criteria andLevel2NameNotEqualTo(String value) {
            addCriterion("level2_name <>", value, "level2Name");
            return (Criteria) this;
        }

        public Criteria andLevel2NameGreaterThan(String value) {
            addCriterion("level2_name >", value, "level2Name");
            return (Criteria) this;
        }

        public Criteria andLevel2NameGreaterThanOrEqualTo(String value) {
            addCriterion("level2_name >=", value, "level2Name");
            return (Criteria) this;
        }

        public Criteria andLevel2NameLessThan(String value) {
            addCriterion("level2_name <", value, "level2Name");
            return (Criteria) this;
        }

        public Criteria andLevel2NameLessThanOrEqualTo(String value) {
            addCriterion("level2_name <=", value, "level2Name");
            return (Criteria) this;
        }

        public Criteria andLevel2NameLike(String value) {
            addCriterion("level2_name like", value, "level2Name");
            return (Criteria) this;
        }

        public Criteria andLevel2NameNotLike(String value) {
            addCriterion("level2_name not like", value, "level2Name");
            return (Criteria) this;
        }

        public Criteria andLevel2NameIn(List<String> values) {
            addCriterion("level2_name in", values, "level2Name");
            return (Criteria) this;
        }

        public Criteria andLevel2NameNotIn(List<String> values) {
            addCriterion("level2_name not in", values, "level2Name");
            return (Criteria) this;
        }

        public Criteria andLevel2NameBetween(String value1, String value2) {
            addCriterion("level2_name between", value1, value2, "level2Name");
            return (Criteria) this;
        }

        public Criteria andLevel2NameNotBetween(String value1, String value2) {
            addCriterion("level2_name not between", value1, value2, "level2Name");
            return (Criteria) this;
        }

        public Criteria andLevel3NameIsNull() {
            addCriterion("level3_name is null");
            return (Criteria) this;
        }

        public Criteria andLevel3NameIsNotNull() {
            addCriterion("level3_name is not null");
            return (Criteria) this;
        }

        public Criteria andLevel3NameEqualTo(String value) {
            addCriterion("level3_name =", value, "level3Name");
            return (Criteria) this;
        }

        public Criteria andLevel3NameNotEqualTo(String value) {
            addCriterion("level3_name <>", value, "level3Name");
            return (Criteria) this;
        }

        public Criteria andLevel3NameGreaterThan(String value) {
            addCriterion("level3_name >", value, "level3Name");
            return (Criteria) this;
        }

        public Criteria andLevel3NameGreaterThanOrEqualTo(String value) {
            addCriterion("level3_name >=", value, "level3Name");
            return (Criteria) this;
        }

        public Criteria andLevel3NameLessThan(String value) {
            addCriterion("level3_name <", value, "level3Name");
            return (Criteria) this;
        }

        public Criteria andLevel3NameLessThanOrEqualTo(String value) {
            addCriterion("level3_name <=", value, "level3Name");
            return (Criteria) this;
        }

        public Criteria andLevel3NameLike(String value) {
            addCriterion("level3_name like", value, "level3Name");
            return (Criteria) this;
        }

        public Criteria andLevel3NameNotLike(String value) {
            addCriterion("level3_name not like", value, "level3Name");
            return (Criteria) this;
        }

        public Criteria andLevel3NameIn(List<String> values) {
            addCriterion("level3_name in", values, "level3Name");
            return (Criteria) this;
        }

        public Criteria andLevel3NameNotIn(List<String> values) {
            addCriterion("level3_name not in", values, "level3Name");
            return (Criteria) this;
        }

        public Criteria andLevel3NameBetween(String value1, String value2) {
            addCriterion("level3_name between", value1, value2, "level3Name");
            return (Criteria) this;
        }

        public Criteria andLevel3NameNotBetween(String value1, String value2) {
            addCriterion("level3_name not between", value1, value2, "level3Name");
            return (Criteria) this;
        }

        public Criteria andLevel1IsNull() {
            addCriterion("level1 is null");
            return (Criteria) this;
        }

        public Criteria andLevel1IsNotNull() {
            addCriterion("level1 is not null");
            return (Criteria) this;
        }

        public Criteria andLevel1EqualTo(String value) {
            addCriterion("level1 =", value, "level1");
            return (Criteria) this;
        }

        public Criteria andLevel1NotEqualTo(String value) {
            addCriterion("level1 <>", value, "level1");
            return (Criteria) this;
        }

        public Criteria andLevel1GreaterThan(String value) {
            addCriterion("level1 >", value, "level1");
            return (Criteria) this;
        }

        public Criteria andLevel1GreaterThanOrEqualTo(String value) {
            addCriterion("level1 >=", value, "level1");
            return (Criteria) this;
        }

        public Criteria andLevel1LessThan(String value) {
            addCriterion("level1 <", value, "level1");
            return (Criteria) this;
        }

        public Criteria andLevel1LessThanOrEqualTo(String value) {
            addCriterion("level1 <=", value, "level1");
            return (Criteria) this;
        }

        public Criteria andLevel1Like(String value) {
            addCriterion("level1 like", value, "level1");
            return (Criteria) this;
        }

        public Criteria andLevel1NotLike(String value) {
            addCriterion("level1 not like", value, "level1");
            return (Criteria) this;
        }

        public Criteria andLevel1In(List<String> values) {
            addCriterion("level1 in", values, "level1");
            return (Criteria) this;
        }

        public Criteria andLevel1NotIn(List<String> values) {
            addCriterion("level1 not in", values, "level1");
            return (Criteria) this;
        }

        public Criteria andLevel1Between(String value1, String value2) {
            addCriterion("level1 between", value1, value2, "level1");
            return (Criteria) this;
        }

        public Criteria andLevel1NotBetween(String value1, String value2) {
            addCriterion("level1 not between", value1, value2, "level1");
            return (Criteria) this;
        }

        public Criteria andLevel2IsNull() {
            addCriterion("level2 is null");
            return (Criteria) this;
        }

        public Criteria andLevel2IsNotNull() {
            addCriterion("level2 is not null");
            return (Criteria) this;
        }

        public Criteria andLevel2EqualTo(String value) {
            addCriterion("level2 =", value, "level2");
            return (Criteria) this;
        }

        public Criteria andLevel2NotEqualTo(String value) {
            addCriterion("level2 <>", value, "level2");
            return (Criteria) this;
        }

        public Criteria andLevel2GreaterThan(String value) {
            addCriterion("level2 >", value, "level2");
            return (Criteria) this;
        }

        public Criteria andLevel2GreaterThanOrEqualTo(String value) {
            addCriterion("level2 >=", value, "level2");
            return (Criteria) this;
        }

        public Criteria andLevel2LessThan(String value) {
            addCriterion("level2 <", value, "level2");
            return (Criteria) this;
        }

        public Criteria andLevel2LessThanOrEqualTo(String value) {
            addCriterion("level2 <=", value, "level2");
            return (Criteria) this;
        }

        public Criteria andLevel2Like(String value) {
            addCriterion("level2 like", value, "level2");
            return (Criteria) this;
        }

        public Criteria andLevel2NotLike(String value) {
            addCriterion("level2 not like", value, "level2");
            return (Criteria) this;
        }

        public Criteria andLevel2In(List<String> values) {
            addCriterion("level2 in", values, "level2");
            return (Criteria) this;
        }

        public Criteria andLevel2NotIn(List<String> values) {
            addCriterion("level2 not in", values, "level2");
            return (Criteria) this;
        }

        public Criteria andLevel2Between(String value1, String value2) {
            addCriterion("level2 between", value1, value2, "level2");
            return (Criteria) this;
        }

        public Criteria andLevel2NotBetween(String value1, String value2) {
            addCriterion("level2 not between", value1, value2, "level2");
            return (Criteria) this;
        }

        public Criteria andSpnameIsNull() {
            addCriterion("spname is null");
            return (Criteria) this;
        }

        public Criteria andSpnameIsNotNull() {
            addCriterion("spname is not null");
            return (Criteria) this;
        }

        public Criteria andSpnameEqualTo(String value) {
            addCriterion("spname =", value, "spname");
            return (Criteria) this;
        }

        public Criteria andSpnameNotEqualTo(String value) {
            addCriterion("spname <>", value, "spname");
            return (Criteria) this;
        }

        public Criteria andSpnameGreaterThan(String value) {
            addCriterion("spname >", value, "spname");
            return (Criteria) this;
        }

        public Criteria andSpnameGreaterThanOrEqualTo(String value) {
            addCriterion("spname >=", value, "spname");
            return (Criteria) this;
        }

        public Criteria andSpnameLessThan(String value) {
            addCriterion("spname <", value, "spname");
            return (Criteria) this;
        }

        public Criteria andSpnameLessThanOrEqualTo(String value) {
            addCriterion("spname <=", value, "spname");
            return (Criteria) this;
        }

        public Criteria andSpnameLike(String value) {
            addCriterion("spname like", value, "spname");
            return (Criteria) this;
        }

        public Criteria andSpnameNotLike(String value) {
            addCriterion("spname not like", value, "spname");
            return (Criteria) this;
        }

        public Criteria andSpnameIn(List<String> values) {
            addCriterion("spname in", values, "spname");
            return (Criteria) this;
        }

        public Criteria andSpnameNotIn(List<String> values) {
            addCriterion("spname not in", values, "spname");
            return (Criteria) this;
        }

        public Criteria andSpnameBetween(String value1, String value2) {
            addCriterion("spname between", value1, value2, "spname");
            return (Criteria) this;
        }

        public Criteria andSpnameNotBetween(String value1, String value2) {
            addCriterion("spname not between", value1, value2, "spname");
            return (Criteria) this;
        }

        public Criteria andLevel3IsNull() {
            addCriterion("level3 is null");
            return (Criteria) this;
        }

        public Criteria andLevel3IsNotNull() {
            addCriterion("level3 is not null");
            return (Criteria) this;
        }

        public Criteria andLevel3EqualTo(String value) {
            addCriterion("level3 =", value, "level3");
            return (Criteria) this;
        }

        public Criteria andLevel3NotEqualTo(String value) {
            addCriterion("level3 <>", value, "level3");
            return (Criteria) this;
        }

        public Criteria andLevel3GreaterThan(String value) {
            addCriterion("level3 >", value, "level3");
            return (Criteria) this;
        }

        public Criteria andLevel3GreaterThanOrEqualTo(String value) {
            addCriterion("level3 >=", value, "level3");
            return (Criteria) this;
        }

        public Criteria andLevel3LessThan(String value) {
            addCriterion("level3 <", value, "level3");
            return (Criteria) this;
        }

        public Criteria andLevel3LessThanOrEqualTo(String value) {
            addCriterion("level3 <=", value, "level3");
            return (Criteria) this;
        }

        public Criteria andLevel3Like(String value) {
            addCriterion("level3 like", value, "level3");
            return (Criteria) this;
        }

        public Criteria andLevel3NotLike(String value) {
            addCriterion("level3 not like", value, "level3");
            return (Criteria) this;
        }

        public Criteria andLevel3In(List<String> values) {
            addCriterion("level3 in", values, "level3");
            return (Criteria) this;
        }

        public Criteria andLevel3NotIn(List<String> values) {
            addCriterion("level3 not in", values, "level3");
            return (Criteria) this;
        }

        public Criteria andLevel3Between(String value1, String value2) {
            addCriterion("level3 between", value1, value2, "level3");
            return (Criteria) this;
        }

        public Criteria andLevel3NotBetween(String value1, String value2) {
            addCriterion("level3 not between", value1, value2, "level3");
            return (Criteria) this;
        }

        public Criteria andLocalBatchNameIsNull() {
            addCriterion("local_batch_name is null");
            return (Criteria) this;
        }

        public Criteria andLocalBatchNameIsNotNull() {
            addCriterion("local_batch_name is not null");
            return (Criteria) this;
        }

        public Criteria andLocalBatchNameEqualTo(String value) {
            addCriterion("local_batch_name =", value, "localBatchName");
            return (Criteria) this;
        }

        public Criteria andLocalBatchNameNotEqualTo(String value) {
            addCriterion("local_batch_name <>", value, "localBatchName");
            return (Criteria) this;
        }

        public Criteria andLocalBatchNameGreaterThan(String value) {
            addCriterion("local_batch_name >", value, "localBatchName");
            return (Criteria) this;
        }

        public Criteria andLocalBatchNameGreaterThanOrEqualTo(String value) {
            addCriterion("local_batch_name >=", value, "localBatchName");
            return (Criteria) this;
        }

        public Criteria andLocalBatchNameLessThan(String value) {
            addCriterion("local_batch_name <", value, "localBatchName");
            return (Criteria) this;
        }

        public Criteria andLocalBatchNameLessThanOrEqualTo(String value) {
            addCriterion("local_batch_name <=", value, "localBatchName");
            return (Criteria) this;
        }

        public Criteria andLocalBatchNameLike(String value) {
            addCriterion("local_batch_name like", value, "localBatchName");
            return (Criteria) this;
        }

        public Criteria andLocalBatchNameNotLike(String value) {
            addCriterion("local_batch_name not like", value, "localBatchName");
            return (Criteria) this;
        }

        public Criteria andLocalBatchNameIn(List<String> values) {
            addCriterion("local_batch_name in", values, "localBatchName");
            return (Criteria) this;
        }

        public Criteria andLocalBatchNameNotIn(List<String> values) {
            addCriterion("local_batch_name not in", values, "localBatchName");
            return (Criteria) this;
        }

        public Criteria andLocalBatchNameBetween(String value1, String value2) {
            addCriterion("local_batch_name between", value1, value2, "localBatchName");
            return (Criteria) this;
        }

        public Criteria andLocalBatchNameNotBetween(String value1, String value2) {
            addCriterion("local_batch_name not between", value1, value2, "localBatchName");
            return (Criteria) this;
        }

        public Criteria andZslxNameIsNull() {
            addCriterion("zslx_name is null");
            return (Criteria) this;
        }

        public Criteria andZslxNameIsNotNull() {
            addCriterion("zslx_name is not null");
            return (Criteria) this;
        }

        public Criteria andZslxNameEqualTo(String value) {
            addCriterion("zslx_name =", value, "zslxName");
            return (Criteria) this;
        }

        public Criteria andZslxNameNotEqualTo(String value) {
            addCriterion("zslx_name <>", value, "zslxName");
            return (Criteria) this;
        }

        public Criteria andZslxNameGreaterThan(String value) {
            addCriterion("zslx_name >", value, "zslxName");
            return (Criteria) this;
        }

        public Criteria andZslxNameGreaterThanOrEqualTo(String value) {
            addCriterion("zslx_name >=", value, "zslxName");
            return (Criteria) this;
        }

        public Criteria andZslxNameLessThan(String value) {
            addCriterion("zslx_name <", value, "zslxName");
            return (Criteria) this;
        }

        public Criteria andZslxNameLessThanOrEqualTo(String value) {
            addCriterion("zslx_name <=", value, "zslxName");
            return (Criteria) this;
        }

        public Criteria andZslxNameLike(String value) {
            addCriterion("zslx_name like", value, "zslxName");
            return (Criteria) this;
        }

        public Criteria andZslxNameNotLike(String value) {
            addCriterion("zslx_name not like", value, "zslxName");
            return (Criteria) this;
        }

        public Criteria andZslxNameIn(List<String> values) {
            addCriterion("zslx_name in", values, "zslxName");
            return (Criteria) this;
        }

        public Criteria andZslxNameNotIn(List<String> values) {
            addCriterion("zslx_name not in", values, "zslxName");
            return (Criteria) this;
        }

        public Criteria andZslxNameBetween(String value1, String value2) {
            addCriterion("zslx_name between", value1, value2, "zslxName");
            return (Criteria) this;
        }

        public Criteria andZslxNameNotBetween(String value1, String value2) {
            addCriterion("zslx_name not between", value1, value2, "zslxName");
            return (Criteria) this;
        }

        public Criteria andYearIsNull() {
            addCriterion("year is null");
            return (Criteria) this;
        }

        public Criteria andYearIsNotNull() {
            addCriterion("year is not null");
            return (Criteria) this;
        }

        public Criteria andYearEqualTo(Integer value) {
            addCriterion("year =", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearNotEqualTo(Integer value) {
            addCriterion("year <>", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearGreaterThan(Integer value) {
            addCriterion("year >", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearGreaterThanOrEqualTo(Integer value) {
            addCriterion("year >=", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearLessThan(Integer value) {
            addCriterion("year <", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearLessThanOrEqualTo(Integer value) {
            addCriterion("year <=", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearIn(List<Integer> values) {
            addCriterion("year in", values, "year");
            return (Criteria) this;
        }

        public Criteria andYearNotIn(List<Integer> values) {
            addCriterion("year not in", values, "year");
            return (Criteria) this;
        }

        public Criteria andYearBetween(Integer value1, Integer value2) {
            addCriterion("year between", value1, value2, "year");
            return (Criteria) this;
        }

        public Criteria andYearNotBetween(Integer value1, Integer value2) {
            addCriterion("year not between", value1, value2, "year");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table school_specialty
     *
     * @mbg.generated do_not_delete_during_merge Fri Aug 21 09:11:04 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table school_specialty
     *
     * @mbg.generated Fri Aug 21 09:11:04 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}