package com.lexiangmiao.sample.mybatis.repository.cee;

import com.lexiangmiao.sample.mybatis.domain.cee.ProvincialScore;
import com.lexiangmiao.sample.mybatis.domain.cee.ProvincialScoreExample;
import com.lexiangmiao.sample.mybatis.domain.cee.ProvincialScoreKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProvincialScoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provincial_score
     *
     * @mbg.generated Tue Jul 28 15:10:18 CST 2020
     */
    long countByExample(ProvincialScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provincial_score
     *
     * @mbg.generated Tue Jul 28 15:10:18 CST 2020
     */
    int deleteByExample(ProvincialScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provincial_score
     *
     * @mbg.generated Tue Jul 28 15:10:18 CST 2020
     */
    int deleteByPrimaryKey(ProvincialScoreKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provincial_score
     *
     * @mbg.generated Tue Jul 28 15:10:18 CST 2020
     */
    int insert(ProvincialScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provincial_score
     *
     * @mbg.generated Tue Jul 28 15:10:18 CST 2020
     */
    int insertSelective(ProvincialScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provincial_score
     *
     * @mbg.generated Tue Jul 28 15:10:18 CST 2020
     */
    List<ProvincialScore> selectByExample(ProvincialScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provincial_score
     *
     * @mbg.generated Tue Jul 28 15:10:18 CST 2020
     */
    ProvincialScore selectByPrimaryKey(ProvincialScoreKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provincial_score
     *
     * @mbg.generated Tue Jul 28 15:10:18 CST 2020
     */
    int updateByExampleSelective(@Param("record") ProvincialScore record, @Param("example") ProvincialScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provincial_score
     *
     * @mbg.generated Tue Jul 28 15:10:18 CST 2020
     */
    int updateByExample(@Param("record") ProvincialScore record, @Param("example") ProvincialScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provincial_score
     *
     * @mbg.generated Tue Jul 28 15:10:18 CST 2020
     */
    int updateByPrimaryKeySelective(ProvincialScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provincial_score
     *
     * @mbg.generated Tue Jul 28 15:10:18 CST 2020
     */
    int updateByPrimaryKey(ProvincialScore record);
}