version: "2"
services:
  mysqldb: #服务名任意取
    networks:
    - mynet
    restart: always
    image: mysql:5.7.25
    volumes:
    - ./mysqldata/:/var/lib/mysql/
    environment:
    - MYSQL_ROOT_PASSWORD=123456
    #    - MYSQL_USER=root
    #    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    - MYSQL_DATABASE=store
    ports:
    - "3306:3306"
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
networks:
  mynet:
    external: true
