server:
  port: 8401
spring:
  application:
    name: sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:18080
        port: 8719 # 客户端用的端口
        clientIp: localhost # 不指定的话，可能不显示图表 参考：https://github.com/alibaba/spring-cloud-alibaba/issues/1220
management:
  endpoints:
    web:
      exposure:
        include: '*'

